In [73]:
filename="pcRNA_full.fa"
# filename="lncRNA.full.fa"

# 1. Fickett_Score

In [74]:
ficket_arr=[]
def calculate_fickett_score(seq):
    """
    Calculates the Fickett score for a given DNA sequence.
    """
    num_a = seq.count('A')
    num_c = seq.count('C')
    num_g = seq.count('G')
    num_t = seq.count('T')
    
    if num_a + num_c + num_g + num_t == 0:
        return 0
    
    freq_a = num_a / (num_a + num_c + num_g + num_t)
    freq_c = num_c / (num_a + num_c + num_g + num_t)
    freq_g = num_g / (num_a + num_c + num_g + num_t)
    freq_t = num_t / (num_a + num_c + num_g + num_t)
    
    r_y_ratio = (freq_a + freq_g) / (freq_c + freq_t)
    a_t_ratio = freq_a / freq_t
    gc_content = freq_g + freq_c
    fickett_score = (r_y_ratio * a_t_ratio) + gc_content - 0.5
    
    return fickett_score

def read_fasta_file(filename):
    """
    Reads a FASTA file and returns a list of (header, sequence) tuples.
    """
    sequences = []
    with open(filename, 'r') as f:
        header = ''
        sequence = ''
        for line in f:
            if line.startswith('>'):
                if header != '':
                    sequences.append((header, sequence))
                header = line.strip()[1:]
                sequence = ''
            else:
                sequence += line.strip().upper()
        if header != '':
            sequences.append((header, sequence))
    return sequences

sequences = read_fasta_file(filename)

for header, sequence in sequences:
    fickett_score = calculate_fickett_score(sequence)
#     print(f'{header}\tFickett score: {fickett_score:.4f}')
    print(f'{fickett_score:.4f}')
    ficket_arr.append(fickett_score)


0.8532
0.4056
0.4056
1.3766
1.3794
1.5629
1.4147
1.4418
1.3507
1.3286
1.4558
1.3747
1.3571
1.2466
1.3373
1.0550
1.1389
1.3875
1.2255
1.2258
0.9779
1.2586
1.2530
1.1979
1.4667
1.2504
1.1785
2.0380
1.7655
1.8933
1.0338
1.0381
1.0243
1.0199
1.2620
1.0502
1.1439
1.1888
1.1778
1.0540
0.8844
0.9062
1.1836
1.1704
1.1662
1.0367
1.0238
0.9691
1.4686
1.4478
1.3455
1.4178
1.0890
1.1528
1.0455
1.2561
1.0082
1.3122
1.3603
1.3832
1.4516
1.2233
1.2538
1.2711
1.2677
1.5475
1.4069
1.3709
1.4368
1.4129
1.3979
1.8620
0.9244
1.0207
0.9772
0.9517
0.9279
1.3271
1.3650
1.3041
1.2406
1.1764
1.1623
1.3381
1.0673
0.9720
1.0381
1.0502
1.3313
1.1288
1.1718
1.0902
1.0867
1.0902
1.3093
1.1425
1.0201
1.1467
1.4567
1.8570
1.1044
1.1763
1.1135
1.3332
1.3668
1.3964
1.3779
1.3175
1.1159
1.4227
1.4085
1.4186
1.3930
1.5804
1.8913
1.3232
1.4591
1.5355
1.1530
1.1862
1.2015
1.1220
1.2108
1.1377
0.9378
1.0651
0.5989
1.2404
1.2134
1.0339
1.3124
1.3326
1.4223
1.3306
0.9472
0.9182
0.9322
0.9150
1.5297
1.5766
1.6160
1.5423
1.1651

0.8959
0.8129
0.9360
1.3162
1.3746
0.9240
0.8410
1.0727
1.0877
1.9714
0.8178
1.1224
1.0361
1.0309
1.3297
1.1867
1.1718
1.1991
1.1431
0.8962
0.9451
0.9573
0.9544
1.0050
1.0327
0.9957
0.9775
0.9405
0.9736
1.1604
1.0719
1.1014
0.7749
0.7625
0.7448
1.0966
1.7299
1.1550
1.1839
1.9525
1.3170
1.0544
0.9646
1.1900
1.0716
1.0829
0.8361
0.8668
0.9031
0.9637
0.9058
0.8942
1.3555
1.3086
1.6402
1.6561
2.6873
0.7700
1.0134
0.8833
1.0253
0.9417
1.0644
1.0741
0.8797
1.6879
0.7460
0.9190
1.0961
1.0398
0.7809
0.7795
1.2435
1.2368
0.9468
1.0935
1.4712
1.1895
1.2069
1.2141
1.1728
1.1975
1.1895
1.0971
0.8842
1.1982
1.1594
1.1997
1.2381
1.1961
1.2032
1.2183
1.4134
1.4112
1.3977
1.6276
1.7647
1.3421
1.6203
1.1151
1.0541
1.0882
1.3835
1.3008
1.3159
1.3354
1.3246
1.2982
1.2662
1.3074
1.2249
1.2005
0.9973
1.0703
1.1562
1.0043
0.9111
0.7274
0.4450
0.3934
0.4065
0.5192
0.7079
0.4128
0.3463
0.9286
1.0992
0.7376
0.9198
0.6788
0.9231
0.9226
1.7219
1.6614
1.4870
1.0806
0.9233
0.7973
0.8335
0.7988
1.3747
2.4300
1.9594

1.1365
1.2007
1.0594
0.9290
1.4591
1.0415
1.0359
1.3654
1.0454
1.1983
0.8810
1.1793
1.4309
1.1577
0.7736
0.9284
0.9677
1.0405
1.0365
1.1166
1.1075
1.0036
1.0748
1.0297
0.9833
1.5096
0.8141
2.2910
1.6760
1.9778
1.8493
1.5338
2.1375
2.6277
1.3843
2.1972
1.8254
3.5456
2.0284
1.0646
0.8232
0.9384
1.4229
0.8286
0.5777
1.3202
1.2863
1.2906
1.7027
1.7687
1.3272
1.7513
1.9350
1.8084
1.2951
1.3816
1.0185
1.2303
1.3055
1.6895
1.2382
1.2464
0.8319
0.8368
1.4395
1.4373
0.9089
1.2633
1.3453
1.4061
1.0208
0.9905
0.9175
1.2043
0.8817
1.1938
0.9634
1.0486
0.9357
1.5281
0.8965
1.2081
1.4736
1.1748
1.2523
0.8918
0.8764
1.2159
0.9307
1.0398
1.5557
1.0647
1.4103
1.0957
0.8513
1.2456
0.5740
1.3924
1.3310
1.2183
1.3865
0.7929
0.7457
1.0252
1.6989
1.6176
1.2138
1.2455
1.2861
1.2257
1.2720
1.2110
1.3060
1.7164
1.1649
1.4521
1.5280
1.4964
1.5561
1.6629
1.8959
1.7450
1.0501
1.4027
1.6885
1.1058
1.3700
1.6064
1.1956
0.9864
0.9051
0.9382
1.2688
1.5289
0.9670
1.0049
1.2012
0.9308
1.2104
1.1895
1.1594
0.9410
1.0058

1.4885
1.2455
1.5456
1.3291
1.5143
1.3291
1.1771
1.1682
1.1927
1.1930
1.1630
1.5793
1.1658
1.1761
1.1957
1.1487
1.7615
1.1690
3.1274
1.4579
0.7324
0.7334
0.7493
0.7687
0.7676
0.7237
0.7261
0.7279
0.7409
0.7194
0.7382
0.7429
0.7289
0.7279
0.7363
0.7405
0.8105
0.8460
0.7493
0.8053
0.8226
0.8436
0.6929
1.0052
1.1667
1.4038
1.4239
1.1632
1.3463
1.2586
1.4239
1.5877
0.7244
1.0230
1.4304
1.2175
0.8303
0.7819
1.0244
1.0058
1.1159
0.7381
1.0015
1.1094
0.9601
1.9613
0.9609
1.2336
1.1104
0.8958
0.9372
1.2179
1.0446
1.0792
1.0752
0.7250
1.6076
0.9104
1.1361
1.0101
1.5492
1.1403
0.9677
1.1288
1.1325
1.0328
1.0187
1.5125
1.1421
1.6115
0.8238
0.9309
0.9121
0.8635
0.8877
1.2662
1.1823
1.2053
0.7146
0.7517
0.7847
1.1088
1.7095
1.7171
1.9581
1.0273
0.9843
0.7698
1.4574
1.4312
1.8821
2.2821
1.2057
1.0421
0.9188
0.9278
0.8795
0.8866
0.9162
0.7596
1.0705
0.8029
0.8131
1.5527
1.4681
1.0786
1.1983
1.1958
1.3839
1.5129
1.0188
1.0261
1.2115
1.2238
0.8552
0.9651
1.0819
1.1176
1.2344
1.1671
1.1638
1.1847
1.1812

1.0765
1.1209
1.3537
1.3617
1.3000
2.0861
1.4838
0.8085
0.9892
0.9255
1.1748
0.9604
1.0578
0.9423
0.9794
1.1069
1.0599
0.8383
0.8158
1.0436
1.0229
1.0373
1.1247
1.3530
1.4260
1.2290
0.9075
0.6042
0.5352
0.8220
0.6580
0.5630
1.3237
1.4417
1.0614
2.3212
1.7795
1.5135
1.4679
1.7451
1.2690
1.3708
1.7858
1.0789
0.9095
1.3354
1.0637
1.0613
1.0100
1.1490
0.8279
0.8136
0.8681
1.1008
1.0679
1.0475
1.0182
1.0484
1.2035
1.8744
1.3380
1.1199
2.2265
0.9353
0.9434
0.9262
0.8784
0.7754
0.6935
1.0062
1.0144
1.8453
1.2777
1.2609
1.4074
0.9255
1.1057
1.1082
1.2813
0.9825
0.9471
0.9844
0.9303
1.4391
2.1424
0.7487
2.2677
0.7291
2.3153
2.2688
1.5088
2.3935
1.2628
2.7435
1.7617
3.1259
0.8846
0.8982
0.9405
0.8989
0.8391
1.6055
0.7894
0.7964
0.7839
0.9514
0.9087
0.9185
1.2116
0.8114
0.9303
1.0896
1.3675
1.0319
1.0045
0.8751
2.9585
1.0617
1.0530
1.1237
0.7851
0.9130
0.8461
0.7543
0.9632
1.9264
1.3567
2.0126
2.6689
3.7232
1.2642
0.8437
0.8497
0.4888
0.7830
0.4836
1.3158
0.7526
0.8121
0.7066
1.5717
1.0635
1.1594

ZeroDivisionError: float division by zero

In [ ]:
ficket_arr

In [75]:
len(ficket_arr)

43175

# 2. CpG Islands

In [ ]:
cpg_arr=[]

from Bio import SeqIO

def calculate_cpg_islands(seq):
    cpg_islands = []
    cpg_count = 0
    in_island = False
    
    for i in range(len(seq)-1):
        if seq[i:i+2].upper() == 'CG':
            cpg_count += 1
            if not in_island:
                in_island = True
        else:
            if cpg_count > 0:
                cpg_islands.append(cpg_count)
                cpg_count = 0
                in_island = False
    
    if cpg_count > 0:
        cpg_islands.append(cpg_count)
    
    return cpg_islands

# Open the FASTA file and loop over each record
for record in SeqIO.parse(filename, "fasta"):
    seq_id = record.id
    seq = record.seq
    
    # Calculate the number of CpG islands for this sequence
    cpg_islands = calculate_cpg_islands(seq)
    num_islands = len(cpg_islands)
    
    # Print the results
#     print(f'{seq_id}\t{num_islands}')
    print(f'\t{num_islands}')
    cpg_arr.append(num_islands)


	18
	8
	8
	302
	302
	29
	162
	123
	131
	141
	120
	137
	136
	110
	124
	199
	70
	145
	117
	131
	30
	152
	128
	124
	135
	114
	83
	50
	41
	37
	535
	540
	545
	540
	94
	139
	117
	127
	128
	181
	123
	73
	61
	69
	63
	24
	20
	30
	133
	135
	34
	99
	15
	62
	76
	35
	58
	75
	60
	63
	67
	69
	65
	54
	55
	58
	51
	61
	148
	166
	167
	44
	256
	85
	151
	147
	156
	70
	79
	79
	68
	73
	91
	38
	56
	54
	54
	66
	42
	53
	154
	114
	165
	148
	30
	145
	51
	258
	158
	34
	89
	79
	118
	109
	91
	102
	90
	92
	115
	90
	82
	103
	107
	86
	43
	58
	38
	33
	39
	37
	40
	51
	29
	27
	29
	19
	21
	135
	29
	181
	207
	271
	63
	59
	122
	157
	148
	181
	92
	59
	55
	70
	146
	95
	139
	103
	57
	53
	40
	32
	18
	35
	131
	48
	57
	117
	31
	139
	30
	216
	283
	31
	164
	23
	224
	143
	174
	178
	140
	143
	54
	123
	65
	52
	92
	142
	197
	266
	290
	292
	281
	291
	45
	301
	87
	273
	89
	302
	52
	260
	251
	228
	37
	118
	57
	118
	138
	126
	81
	68
	66
	32
	160
	148
	142
	125
	112
	135
	139
	138
	114
	246
	228
	146
	127
	121
	114
	126
	125
	128
	118
	25
	3

	91
	47
	6
	46
	57
	63
	28
	49
	26
	49
	25
	62
	54
	43
	35
	42
	30
	48
	50
	51
	65
	30
	32
	22
	26
	16
	11
	23
	20
	32
	36
	34
	29
	83
	31
	32
	77
	35
	70
	66
	66
	28
	273
	103
	104
	60
	77
	81
	54
	56
	77
	48
	45
	96
	91
	87
	64
	75
	74
	118
	75
	87
	66
	67
	71
	57
	42
	38
	46
	11
	13
	134
	136
	106
	112
	76
	58
	62
	62
	26
	273
	283
	276
	257
	2
	118
	43
	146
	108
	104
	115
	116
	117
	101
	77
	100
	128
	98
	23
	22
	19
	15
	14
	15
	25
	26
	9
	124
	33
	16
	29
	10
	20
	20
	17
	18
	27
	25
	14
	14
	19
	15
	9
	86
	81
	93
	102
	116
	112
	81
	79
	79
	52
	45
	26
	160
	20
	19
	118
	25
	226
	230
	268
	296
	328
	235
	228
	118
	80
	32
	54
	79
	49
	79
	22
	19
	7
	14
	35
	107
	44
	12
	13
	13
	14
	9
	14
	13
	2
	101
	70
	33
	72
	61
	85
	59
	21
	75
	82
	33
	49
	29
	26
	35
	55
	18
	28
	28
	30
	30
	21
	26
	17
	55
	60
	60
	50
	58
	42
	41
	33
	42
	21
	41
	42
	35
	34
	31
	42
	42
	42
	34
	39
	57
	40
	37
	40
	41
	56
	35
	57
	40
	33
	24
	71
	37
	34
	29
	36
	73
	82
	78
	17
	22
	13
	43
	75
	53
	70
	31
	55
	9
	2

	80
	49
	84
	93
	63
	65
	61
	13
	18
	29
	24
	15
	29
	24
	26
	41
	57
	15
	19
	315
	98
	34
	67
	3
	2
	3
	4
	32
	60
	65
	65
	39
	86
	75
	44
	5
	102
	94
	49
	46
	20
	117
	116
	118
	115
	115
	89
	116
	120
	137
	36
	36
	37
	75
	35
	1
	11
	20
	24
	7
	2
	8
	46
	40
	43
	12
	49
	10
	16
	15
	18
	31
	18
	12
	6
	38
	7
	9
	6
	46
	96
	16
	3
	10
	16
	40
	13
	12
	8
	37
	38
	19
	4
	68
	43
	53
	35
	36
	59
	61
	62
	67
	67
	57
	58
	62
	58
	57
	55
	84
	59
	57
	63
	58
	59
	43
	37
	31
	29
	27
	26
	26
	23
	19
	29
	27
	28
	35
	21
	24
	14
	18
	20
	21
	17
	20
	25
	17
	19
	6
	16
	39
	8
	50
	15
	69
	88
	36
	33
	9
	25
	78
	79
	12
	10
	23
	46
	44
	14
	24
	58
	25
	38
	62
	49
	5
	17
	7
	11
	58
	32
	50
	27
	54
	56
	81
	68
	38
	56
	46
	29
	35
	44
	32
	37
	32
	2
	34
	10
	23
	65
	22
	58
	39
	41
	18
	6
	14
	14
	12
	34
	17
	11
	9
	17
	12
	20
	10
	5
	6
	32
	42
	22
	27
	22
	36
	18
	3
	5
	5
	5
	74
	76
	77
	74
	78
	75
	65
	70
	76
	80
	80
	81
	84
	82
	75
	74
	75
	80
	79
	76
	76
	103
	81
	76
	62
	26
	95
	70
	87
	39
	50
	65
	27
	30

	404
	25
	298
	293
	55
	26
	6
	49
	11
	10
	5
	5
	5
	8
	6
	9
	8
	11
	8
	12
	64
	14
	5
	10
	3
	10
	11
	5
	10
	10
	8
	6
	1
	8
	12
	6
	6
	2
	5
	5
	2
	3
	5
	6
	6
	6
	6
	6
	3
	3
	6
	5
	7
	5
	118
	31
	27
	24
	24
	15
	5
	8
	8
	36
	8
	8
	7
	9
	11
	33
	19
	15
	14
	11
	11
	11
	9
	10
	21
	15
	7
	7
	5
	3
	5
	4
	20
	21
	16
	24
	8
	8
	9
	10
	14
	9
	9
	12
	14
	13
	10
	12
	7
	79
	60
	69
	58
	35
	25
	34
	22
	26
	7
	15
	210
	115
	90
	79
	77
	49
	10
	167
	130
	45
	18
	14
	28
	123
	57
	41
	21
	50
	42
	22
	7
	225
	137
	30
	60
	39
	42
	72
	53
	39
	45
	59
	37
	55
	64
	49
	30
	49
	20
	30
	30
	16
	25
	23
	9
	60
	44
	63
	14
	99
	21
	33
	9
	21
	18
	74
	70
	55
	35
	39
	32
	28
	36
	33
	25
	17
	30
	13
	24
	30
	86
	17
	20
	11
	4
	8
	44
	49
	41
	40
	42
	42
	40
	44
	36
	75
	81
	94
	24
	39
	27
	84
	35
	29
	84
	38
	33
	33
	31
	32
	32
	31
	22
	29
	22
	30
	28
	30
	23
	28
	15
	25
	19
	23
	54
	55
	162
	50
	138
	152
	110
	123
	149
	30
	36
	22
	12
	81
	177
	133
	47
	85
	189
	166
	136
	152
	153
	162
	134
	128
	124
	123
	148
	14

	37
	22
	23
	339
	256
	308
	189
	58
	18
	72
	149
	12
	38
	53
	30
	22
	103
	101
	53
	57
	37
	11
	118
	69
	80
	29
	44
	36
	38
	116
	55
	74
	74
	62
	78
	54
	56
	34
	41
	36
	48
	21
	14
	21
	20
	20
	20
	19
	18
	138
	93
	94
	22
	84
	16
	9
	9
	11
	14
	13
	8
	186
	188
	52
	52
	51
	95
	5
	6
	36
	31
	10
	19
	100
	103
	139
	10
	153
	137
	120
	139
	131
	124
	126
	128
	69
	112
	16
	21
	10
	81
	66
	26
	38
	42
	30
	56
	16
	50
	36
	27
	27
	32
	14
	67
	221
	211
	207
	199
	128
	126
	114
	22
	46
	95
	108
	37
	104
	76
	32
	55
	42
	23
	51
	37
	36
	36
	46
	51
	53
	46
	169
	42
	15
	147
	143
	115
	7
	12
	45
	28
	51
	143
	65
	19
	39
	72
	60
	105
	57
	63
	67
	1
	17
	6
	150
	35
	9
	76
	11
	75
	97
	17
	17
	20
	14
	13
	22
	43
	41
	38
	25
	189
	178
	169
	77
	14
	74
	113
	121
	113
	190
	187
	235
	67
	16
	43
	128
	137
	139
	134
	132
	136
	137
	8
	6
	5
	7
	104
	96
	152
	301
	104
	103
	191
	211
	201
	269
	284
	25
	180
	178
	74
	33
	69
	153
	171
	179
	53
	185
	183
	193
	218
	189
	129
	101
	100
	14
	67
	68
	134
	148
	19


	163
	44
	34
	7
	76
	81
	80
	83
	84
	82
	32
	62
	59
	15
	318
	70
	34
	66
	318
	81
	179
	114
	94
	126
	129
	40
	91
	136
	132
	23
	19
	17
	76
	207
	37
	201
	195
	15
	71
	127
	80
	79
	31
	55
	9
	9
	43
	40
	6
	42
	58
	56
	64
	45
	35
	35
	34
	30
	29
	30
	30
	38
	26
	28
	27
	26
	170
	60
	51
	31
	12
	8
	35
	23
	16
	21
	41
	43
	69
	71
	48
	50
	4
	19
	31
	8
	98
	92
	11
	8
	3
	28
	63
	74
	15
	68
	86
	72
	78
	72
	83
	17
	25
	119
	19
	18
	45
	86
	88
	41
	58
	23
	66
	60
	31
	128
	145
	76
	27
	50
	57
	59
	76
	45
	9
	11
	6
	12
	18
	154
	32
	12
	149
	75
	17
	50
	120
	38
	4
	321
	35
	37
	34
	37
	26
	36
	27
	16
	12
	13
	7
	11
	193
	77
	52
	52
	47
	34
	293
	115
	134
	40
	10
	72
	36
	108
	69
	96
	92
	14
	35
	39
	8
	34
	31
	29
	25
	12
	16
	20
	21
	7
	6
	10
	4
	66
	48
	22
	16
	31
	38
	36
	49
	26
	19
	6
	100
	132
	23
	8
	85
	15
	59
	32
	130
	124
	105
	64
	81
	81
	34
	115
	94
	90
	226
	271
	114
	174
	21
	41
	109
	22
	29
	69
	56
	42
	213
	170
	138
	96
	88
	96
	88
	113
	83
	75
	269
	274
	133
	171
	110
	137
	103

	99
	69
	21
	38
	30
	119
	175
	132
	46
	41
	25
	38
	48
	16
	99
	121
	68
	30
	134
	186
	22
	41
	42
	15
	69
	60
	87
	80
	72
	77
	77
	98
	73
	64
	87
	62
	27
	48
	82
	67
	58
	44
	39
	40
	32
	42
	22
	137
	139
	87
	45
	76
	34
	32
	36
	86
	188
	151
	36
	85
	31
	63
	39
	64
	29
	32
	28
	18
	60
	26
	37
	35
	6
	5
	2
	69
	81
	4
	56
	4
	26
	45
	46
	49
	45
	40
	32
	27
	23
	6
	7
	4
	10
	6
	9
	13
	13
	15
	6
	114
	122
	18
	118
	106
	13
	7
	50
	49
	51
	48
	10
	153
	194
	181
	132
	63
	58
	36
	28
	29
	19
	182
	82
	69
	49
	24
	64
	163
	34
	15
	165
	8
	129
	154
	85
	85
	78
	67
	48
	48
	40
	17
	21
	78
	40
	54
	47
	21
	45
	40
	7
	43
	6
	34
	32
	29
	10
	11
	34
	34
	36
	39
	23
	21
	27
	35
	61
	45
	32
	31
	26
	26
	20
	50
	50
	111
	69
	71
	64
	77
	83
	65
	77
	66
	68
	69
	60
	19
	17
	15
	23
	21
	16
	17
	25
	21
	19
	9
	16
	11
	43
	43
	53
	22
	14
	6
	18
	22
	42
	42
	23
	77
	72
	68
	51
	64
	5
	87
	46
	48
	89
	75
	77
	49
	53
	15
	21
	23
	27
	19
	197
	80
	42
	39
	41
	41
	50
	54
	56
	58
	72
	42
	44
	66
	37
	48
	67
	60
	

	90
	88
	87
	87
	88
	58
	84
	59
	56
	14
	109
	22
	107
	107
	107
	50
	105
	106
	105
	105
	109
	107
	6
	22
	16
	16
	44
	89
	11
	87
	84
	56
	47
	12
	41
	12
	7
	12
	23
	4
	21
	116
	96
	96
	97
	96
	120
	97
	100
	95
	103
	68
	68
	69
	76
	102
	109
	73
	74
	72
	54
	135
	134
	129
	135
	135
	112
	115
	119
	124
	119
	115
	114
	116
	56
	104
	65
	1
	112
	116
	106
	93
	35
	6
	12
	53
	29
	5
	50
	45
	38
	25
	14
	122
	32
	33
	35
	114
	24
	114
	112
	131
	87
	62
	87
	85
	25
	25
	8
	18
	16
	18
	15
	5
	8
	25
	15
	6
	22
	21
	6
	4
	96
	42
	40
	13
	34
	24
	20
	22
	8
	22
	17
	25
	19
	322
	65
	104
	103
	131
	132
	13
	27
	29
	49
	41
	8
	18
	35
	31
	47
	63
	59
	62
	42
	60
	28
	55
	74
	66
	41
	39
	11
	11
	28
	12
	6
	22
	31
	22
	22
	20
	30
	18
	25
	35
	10
	63
	8
	3
	24
	20
	13
	11
	21
	17
	5
	10
	37
	31
	23
	16
	7
	27
	10
	148
	50
	51
	26
	29
	81
	82
	88
	55
	15
	193
	20
	77
	32
	32
	49
	48
	42
	41
	28
	36
	30
	5
	29
	64
	118
	75
	91
	51
	59
	40
	37
	125
	12
	34
	72
	36
	38
	56
	99
	105
	57
	28
	24
	88
	9
	104
	113

	66
	64
	56
	64
	47
	51
	61
	62
	55
	65
	6
	24
	100
	84
	85
	210
	184
	183
	140
	86
	126
	72
	104
	37
	484
	429
	359
	75
	72
	268
	136
	30
	113
	15
	7
	19
	20
	195
	212
	196
	199
	192
	35
	85
	24
	121
	86
	97
	13
	15
	8
	13
	23
	35
	122
	119
	71
	71
	97
	86
	75
	72
	241
	120
	61
	32
	85
	84
	91
	92
	102
	93
	95
	93
	93
	92
	93
	92
	89
	80
	87
	88
	72
	84
	83
	21
	65
	63
	10
	75
	28
	5
	10
	27
	30
	61
	49
	37
	37
	35
	23
	14
	26
	12
	20
	14
	35
	21
	82
	83
	46
	40
	71
	71
	55
	62
	33
	47
	11
	45
	47
	45
	130
	130
	16
	45
	49
	10
	13
	10
	7
	130
	156
	132
	130
	148
	48
	46
	25
	17
	39
	134
	154
	24
	319
	13
	78
	20
	19
	11
	66
	10
	17
	8
	157
	21
	15
	2
	5
	111
	13
	14
	11
	35
	34
	26
	49
	52
	27
	40
	43
	38
	50
	41
	21
	25
	26
	40
	33
	36
	9
	30
	20
	27
	18
	22
	6
	7
	75
	102
	41
	37
	38
	6
	6
	11
	9
	12
	8
	78
	24
	14
	41
	46
	41
	40
	37
	5
	28
	5
	9
	12
	11
	11
	15
	6
	6
	69
	27
	11
	17
	109
	107
	77
	79
	73
	31
	31
	126
	140
	140
	138
	140
	110
	116
	124
	115
	100
	103
	33
	95
	107
	

	104
	123
	63
	42
	46
	19
	37
	20
	32
	17
	22
	42
	47
	27
	57
	50
	49
	42
	39
	48
	44
	50
	41
	47
	39
	46
	27
	28
	26
	14
	23
	22
	144
	85
	45
	53
	47
	45
	42
	33
	49
	37
	39
	18
	32
	28
	41
	70
	43
	8
	26
	16
	17
	13
	7
	6
	70
	13
	51
	20
	32
	22
	83
	31
	26
	61
	21
	42
	7
	6
	25
	115
	38
	65
	58
	111
	86
	92
	94
	93
	86
	85
	100
	91
	41
	140
	125
	49
	21
	34
	33
	2
	36
	12
	60
	32
	45
	12
	71
	14
	5
	5
	4
	50
	49
	19
	63
	59
	16
	25
	33
	24
	23
	101
	101
	34
	41
	72
	81
	114
	102
	29
	67
	12
	41
	7
	39
	65
	23
	21
	60
	64
	63
	59
	44
	18
	10
	39
	54
	52
	14
	40
	53
	46
	43
	28
	20
	9
	10
	258
	46
	55
	53
	44
	18
	13
	18
	22
	23
	33
	66
	118
	144
	90
	66
	25
	73
	48
	48
	43
	49
	12
	45
	43
	138
	78
	86
	18
	33
	104
	135
	147
	83
	126
	80
	69
	11
	66
	10
	6
	21
	27
	29
	27
	14
	13
	76
	77
	37
	35
	37
	70
	12
	16
	108
	66
	11
	49
	11
	53
	13
	11
	14
	10
	11
	12
	19
	18
	12
	12
	11
	50
	7
	15
	6
	4
	12
	15
	17
	32
	48
	57
	35
	33
	141
	82
	235
	232
	221
	135
	159
	15
	95
	12
	10
	45
	35


	122
	158
	141
	106
	58
	24
	46
	6
	51
	24
	26
	32
	154
	157
	152
	14
	232
	192
	10
	94
	98
	226
	268
	184
	192
	108
	150
	107
	122
	87
	8
	56
	32
	43
	49
	36
	47
	34
	37
	119
	35
	46
	28
	48
	70
	19
	21
	248
	256
	14
	13
	43
	14
	33
	17
	36
	30
	27
	24
	64
	37
	18
	61
	70
	15
	47
	27
	24
	23
	21
	76
	72
	63
	53
	22
	20
	26
	18
	19
	9
	1
	49
	25
	23
	13
	60
	38
	36
	118
	67
	5
	24
	10
	8
	17
	42
	8
	78
	76
	98
	93
	16
	20
	59
	77
	77
	36
	52
	44
	66
	41
	14
	32
	25
	150
	167
	134
	98
	52
	102
	63
	49
	65
	146
	51
	52
	66
	47
	76
	60
	94
	115
	51
	104
	112
	88
	47
	68
	46
	46
	52
	82
	40
	39
	32
	27
	9
	5
	8
	20
	68
	47
	13
	40
	33
	86
	70
	50
	107
	82
	54
	54
	37
	18
	41
	12
	194
	37
	46
	80
	63
	60
	27
	9
	39
	112
	11
	12
	29
	49
	27
	19
	3
	8
	15
	282
	82
	147
	144
	150
	86
	116
	93
	27
	27
	18
	40
	42
	7
	21
	126
	117
	125
	91
	120
	106
	164
	150
	126
	118
	100
	105
	102
	114
	12
	26
	128
	196
	195
	151
	110
	9
	7
	3
	69
	36
	115
	27
	21
	12
	128
	81
	12
	40
	34
	46
	40
	46
	16
	14


	20
	109
	10
	58
	7
	13
	52
	106
	90
	25
	25
	18
	79
	19
	20
	65
	22
	30
	28
	42
	32
	28
	19
	97
	77
	32
	55
	46
	22
	15
	6
	4
	199
	149
	30
	23
	23
	73
	22
	24
	5
	14
	14
	16
	5
	3
	47
	42
	7
	103
	48
	50
	6
	4
	36
	91
	88
	39
	1
	24
	23
	3
	80
	90
	6
	89
	29
	8
	38
	10
	10
	9
	11
	7
	8
	26
	4
	26
	111
	111
	98
	18
	17
	74
	82
	32
	20
	23
	3
	189
	7
	88
	19
	84
	56
	61
	10
	13
	269
	44
	5
	5
	156
	47
	22
	24
	74
	35
	116
	97
	109
	29
	74
	108
	107
	72
	72
	74
	78
	115
	20
	43
	33
	39
	23
	45
	35
	28
	13
	14
	3
	2
	2
	19
	14
	21
	20
	14
	18
	10
	9
	17
	8
	10
	29
	12
	15
	9
	13
	2
	11
	14
	17
	32
	8
	8
	10
	160
	159
	160
	120
	114
	69
	56
	16
	23
	37
	246
	67
	60
	59
	61
	19
	18
	18
	26
	33
	8
	7
	33
	15
	24
	49
	44
	26
	48
	24
	17
	19
	11
	64
	64
	54
	58
	10
	65
	78
	17
	33
	11
	40
	32
	4
	21
	9
	14
	19
	20
	14
	13
	23
	7
	117
	91
	79
	9
	9
	17
	50
	53
	38
	53
	37
	19
	16
	23
	24
	21
	61
	28
	25
	19
	13
	23
	15
	9
	6
	12
	4
	4
	12
	6
	7
	34
	45
	26
	35
	27
	33
	31
	13
	34
	25
	25
	22
	

	140
	34
	25
	99
	21
	104
	162
	129
	75
	110
	47
	23
	10
	83
	86
	129
	83
	84
	79
	82
	138
	117
	109
	101
	113
	104
	103
	79
	78
	406
	407
	409
	412
	396
	4
	13
	15
	13
	112
	126
	103
	124
	243
	243
	137
	254
	134
	21
	132
	131
	134
	134
	126
	106
	376
	72
	73
	189
	233
	92
	45
	21
	38
	24
	19
	70
	83
	83
	6
	12
	13
	208
	138
	39
	42
	101
	68
	73
	73
	44
	51
	67
	23
	136
	24
	16
	18
	119
	86
	59
	60
	133
	142
	137
	125
	219
	101
	135
	189
	97
	223
	471
	193
	45
	134
	172
	176
	127
	124
	164
	159
	160
	162
	170
	72
	0
	195
	201
	200
	199
	165
	181
	28
	30
	30
	47
	176
	117
	123
	199
	87
	81
	83
	19
	163
	211
	279
	119
	67
	54
	139
	103
	89
	11
	55
	89
	39
	134
	129
	57
	157
	175
	33
	120
	141
	112
	10
	117
	32
	204
	80
	135
	34
	60
	61
	60
	331
	234
	42
	139
	218
	259
	260
	227
	10
	176
	179
	186
	132


In [ ]:
cpg_arr

# 3. GC_Content

In [39]:
gc_arr=[]

def gc_content(seq):
    gc_count = seq.count('G') + seq.count('C')
    total_count = len(seq)
    return (gc_count / total_count) * 100

def fasta_to_gc_content(fasta_file):
    with open(fasta_file) as f:
        seq = ''
        for line in f:
            if line.startswith('>'):
                if seq:
                    gc = gc_content(seq)
                    print(f'{gc:.2f}%\n')
                    gc_arr.append(gc)
                    seq = ''
                header = line.strip()
            else:
                seq += line.strip()
        if seq:
            gc = gc_content(seq)
#             print(f'Sequence: {header}\nGC content: {gc:.2f}%\n')
            print(f'{gc:.2f}%\n')
            gc_arr.append(gc)

fasta_to_gc_content(filename)


35.94%

46.01%

46.01%

69.93%

69.93%

64.34%

66.76%

68.47%

69.03%

69.06%

68.76%

69.08%

66.77%

69.79%

59.81%

64.98%

66.70%

64.58%

65.82%

66.15%

64.04%

65.57%

65.30%

66.29%

73.94%

73.79%

74.51%

63.41%

63.93%

64.21%

67.58%

67.53%

67.87%

67.95%

65.58%

65.66%

66.38%

66.42%

66.56%

66.37%

65.88%

63.63%

67.10%

66.03%

68.24%

66.43%

66.96%

63.56%

65.03%

64.98%

67.25%

62.72%

57.51%

68.63%

68.05%

65.61%

67.66%

69.70%

69.86%

69.30%

69.59%

68.98%

68.95%

69.17%

69.02%

68.60%

69.66%

69.46%

63.32%

63.73%

63.82%

60.16%

64.21%

69.21%

59.31%

59.51%

60.20%

59.51%

58.60%

60.55%

58.18%

60.31%

62.50%

59.75%

61.40%

61.92%

59.58%

66.41%

60.94%

63.07%

64.95%

64.59%

65.41%

66.50%

66.20%

66.18%

67.06%

65.59%

64.56%

61.86%

65.23%

68.07%

60.90%

60.89%

61.33%

60.69%

61.52%

61.72%

61.07%

61.18%

61.93%

61.34%

61.48%

60.30%

58.70%

61.08%

58.88%

60.28%

60.19%

60.00%

60.88%

58.51%

60.82%

62.84%

63.54%



In [40]:
gc_arr

[35.94346829640948,
 46.00638977635783,
 46.00638977635783,
 69.92784992784993,
 69.92502883506344,
 64.34108527131784,
 66.75791943684006,
 68.46689895470384,
 69.03225806451613,
 69.05807711078576,
 68.76122082585279,
 69.08358509566969,
 66.77316293929712,
 69.78625072212594,
 59.8113891911498,
 64.97857421114142,
 66.70317634173057,
 64.57808564231739,
 65.8158614402917,
 66.15071283095723,
 64.04011461318052,
 65.56818181818181,
 65.30477759472817,
 66.29258517034067,
 73.9423076923077,
 73.78531073446327,
 74.5127436281859,
 63.40533672172808,
 63.926940639269404,
 64.2072213500785,
 67.58121758121757,
 67.52772518258047,
 67.874816102715,
 67.95356371490281,
 65.57894736842104,
 65.66488266776452,
 66.37554585152839,
 66.4179104477612,
 66.55550262029539,
 66.3658991910392,
 65.87779690189329,
 63.62807657247037,
 67.10213776722091,
 66.02870813397129,
 68.24324324324324,
 66.4259927797834,
 66.95652173913044,
 63.55785837651122,
 65.03496503496503,
 64.97615951452103,
 67.25352

# 4. Hexamer Score

In [41]:
hexa_arr=[]

from collections import Counter

def hexamer_score(seq):
    hexamers = [seq[i:i+6] for i in range(len(seq)-5)]
    counts = Counter(hexamers)
    score = sum(counts.values())
    return score

def fasta_to_hexamer_score(fasta_file):
    with open(fasta_file) as f:
        seq = ''
        for line in f:
            if line.startswith('>'):
                if seq:
                    score = hexamer_score(seq)
                    print(f'{score}\n')
                    hexa_arr.append(score)
                    seq = ''
                header = line.strip()
            else:
                seq += line.strip()
        if seq:
            score = hexamer_score(seq)
#             print(f'Sequence: {header}\nHexamer score: {score}\n')
            print(f'{score}\n')
            hexa_arr.append(score)

fasta_to_hexamer_score(filename)


2613

934

934

3460

3463

382

2552

1717

1855

2044

1666

1981

2186

1726

2752

2562

908

3171

2189

2450

693

3515

3030

2490

1035

880

662

782

652

632

7321

7389

7472

7403

1895

2424

1827

2005

2094

3209

2319

1092

837

831

735

549

570

574

2283

2302

563

2109

421

846

1078

722

700

1147

1007

1070

1179

1062

1148

806

873

941

954

997

1928

2074

2090

723

2800

1031

2450

2255

2382

1052

1251

1042

1016

1023

1051

467

881

809

762

638

525

745

3045

2263

3470

2726

640

2674

918

3788

2275

577

1252

872

2624

2258

1857

2109

1827

1863

2566

1793

1613

1834

1999

1519

811

1051

654

574

844

745

795

1099

480

544

549

579

574

2149

778

3470

2921

3300

780

773

2226

2288

1996

2723

1067

793

748

870

3107

2054

2810

1593

1181

656

543

695

583

1044

2019

1627

1971

1501

871

3212

814

2142

4487

453

3859

520

4093

2109

2476

2607

2261

2325

825

1376

712

791

1279

4171

2119

3029

In [42]:
hexa_arr

[2613,
 934,
 934,
 3460,
 3463,
 382,
 2552,
 1717,
 1855,
 2044,
 1666,
 1981,
 2186,
 1726,
 2752,
 2562,
 908,
 3171,
 2189,
 2450,
 693,
 3515,
 3030,
 2490,
 1035,
 880,
 662,
 782,
 652,
 632,
 7321,
 7389,
 7472,
 7403,
 1895,
 2424,
 1827,
 2005,
 2094,
 3209,
 2319,
 1092,
 837,
 831,
 735,
 549,
 570,
 574,
 2283,
 2302,
 563,
 2109,
 421,
 846,
 1078,
 722,
 700,
 1147,
 1007,
 1070,
 1179,
 1062,
 1148,
 806,
 873,
 941,
 954,
 997,
 1928,
 2074,
 2090,
 723,
 2800,
 1031,
 2450,
 2255,
 2382,
 1052,
 1251,
 1042,
 1016,
 1023,
 1051,
 467,
 881,
 809,
 762,
 638,
 525,
 745,
 3045,
 2263,
 3470,
 2726,
 640,
 2674,
 918,
 3788,
 2275,
 577,
 1252,
 872,
 2624,
 2258,
 1857,
 2109,
 1827,
 1863,
 2566,
 1793,
 1613,
 1834,
 1999,
 1519,
 811,
 1051,
 654,
 574,
 844,
 745,
 795,
 1099,
 480,
 544,
 549,
 579,
 574,
 2149,
 778,
 3470,
 2921,
 3300,
 780,
 773,
 2226,
 2288,
 1996,
 2723,
 1067,
 793,
 748,
 870,
 3107,
 2054,
 2810,
 1593,
 1181,
 656,
 543,
 695,
 583,
 1

# 5. ORF_Length

In [43]:
orf_arr=[]

def read_fasta_file(filename):
    """
    Reads a FASTA file and returns a list of (header, sequence) tuples.
    """
    sequences = []
    with open(filename, 'r') as f:
        header = ''
        sequence = ''
        for line in f:
            if line.startswith('>'):
                if header != '':
                    sequences.append((header, sequence))
                header = line.strip()[1:]
                sequence = ''
            else:
                sequence += line.strip().upper()
        if header != '':
            sequences.append((header, sequence))
    return sequences

def find_longest_orf(sequence):
    """
    Finds the longest ORF in a given DNA sequence.
    """
    longest_orf_length = 0
    for frame in range(3):
        for pos in range(frame, len(sequence)-2, 3):
            codon = sequence[pos:pos+3]
            if codon == 'ATG':
                orf_length = 0
                for pos2 in range(pos, len(sequence)-2, 3):
                    codon2 = sequence[pos2:pos2+3]
                    if codon2 in ('TAA', 'TAG', 'TGA'):
                        break
                    else:
                        orf_length += 3
                if orf_length > longest_orf_length:
                    longest_orf_length = orf_length
    return longest_orf_length

sequences = read_fasta_file(filename)

for header, sequence in sequences:
    orf_length = find_longest_orf(sequence)
#     print(f'{header}\tORF length: {orf_length}')
    print(f'{orf_length}')
    orf_arr.append(orf_length)

978
936
936
2532
2535
327
2043
1719
1857
2046
1668
1983
1752
1587
2247
1926
384
1833
1728
1989
387
2370
2028
2370
741
663
567
471
429
495
6135
6204
5889
5820
747
1140
594
567
390
762
1032
594
669
309
354
222
210
147
2019
2019
435
1212
243
765
723
507
702
894
1005
831
1065
609
909
567
759
702
933
975
1086
1044
762
720
987
906
672
777
621
621
621
777
825
558
588
180
513
237
300
303
213
129
2406
1680
1914
1914
417
2112
840
2502
2277
402
909
375
1818
1713
1506
1800
1506
1026
1818
1497
1281
1734
1713
834
519
1032
327
453
714
627
747
867
420
174
501
174
330
663
351
2556
2010
2085
480
750
1023
1326
1350
1299
597
597
597
597
1560
894
894
894
678
540
261
447
117
465
1197
261
522
1197
522
489
501
699
1335
444
1233
393
1944
1626
1758
1902
1227
1521
726
519
519
336
582
459
678
2562
2997
3039
2844
3027
342
2448
252
2259
525
2907
444
2757
1185
2457
267
384
498
1170
714
1158
513
510
459
228
2346
2385
2244
1695
1578
2316
2349
2355
738
1215
1215
2340
2238
2238
1260
2337
2310
2349
1221
453
111
1338
1338

1356
690
1263
816
1263
816
1425
1356
1116
444
849
861
663
663
684
663
663
582
483
639
483
237
483
597
483
408
486
315
654
1689
1719
1689
600
1737
1737
1587
723
1116
1803
1965
1695
1626
1632
1764
1923
1626
2325
2025
2592
2361
2298
1821
2421
2244
2592
1443
2346
2160
2523
2484
2040
831
1176
1098
375
654
921
921
1482
1113
1134
480
1119
891
498
4338
4308
4299
4320
168
1488
786
1326
1152
2832
3558
3567
3564
3324
2562
3486
3672
3381
156
669
534
378
612
282
747
387
288
621
408
378
1071
507
438
699
537
480
789
723
723
750
399
267
396
1392
1377
1365
1377
1308
1401
1086
849
1275
1275
1167
852
4812
387
498
2898
411
4500
4497
4752
4398
4755
4653
4662
2526
1521
180
2088
3648
1917
3609
435
291
261
399
501
501
501
408
426
219
198
207
189
66
63
1329
1212
576
1476
879
1608
933
927
1638
1638
600
723
387
345
1398
1638
1047
288
492
492
540
492
420
201
975
975
975
831
975
576
1086
924
969
498
747
972
576
1071
543
876
756
975
348
810
1314
1065
1041
747
651
1221
882
1149
897
825
804
390
423
582
489
357
1374
1

In [44]:
orf_arr

[978,
 936,
 936,
 2532,
 2535,
 327,
 2043,
 1719,
 1857,
 2046,
 1668,
 1983,
 1752,
 1587,
 2247,
 1926,
 384,
 1833,
 1728,
 1989,
 387,
 2370,
 2028,
 2370,
 741,
 663,
 567,
 471,
 429,
 495,
 6135,
 6204,
 5889,
 5820,
 747,
 1140,
 594,
 567,
 390,
 762,
 1032,
 594,
 669,
 309,
 354,
 222,
 210,
 147,
 2019,
 2019,
 435,
 1212,
 243,
 765,
 723,
 507,
 702,
 894,
 1005,
 831,
 1065,
 609,
 909,
 567,
 759,
 702,
 933,
 975,
 1086,
 1044,
 762,
 720,
 987,
 906,
 672,
 777,
 621,
 621,
 621,
 777,
 825,
 558,
 588,
 180,
 513,
 237,
 300,
 303,
 213,
 129,
 2406,
 1680,
 1914,
 1914,
 417,
 2112,
 840,
 2502,
 2277,
 402,
 909,
 375,
 1818,
 1713,
 1506,
 1800,
 1506,
 1026,
 1818,
 1497,
 1281,
 1734,
 1713,
 834,
 519,
 1032,
 327,
 453,
 714,
 627,
 747,
 867,
 420,
 174,
 501,
 174,
 330,
 663,
 351,
 2556,
 2010,
 2085,
 480,
 750,
 1023,
 1326,
 1350,
 1299,
 597,
 597,
 597,
 597,
 1560,
 894,
 894,
 894,
 678,
 540,
 261,
 447,
 117,
 465,
 1197,
 261,
 522,
 1197,
 522

# 6. Transcript_length

In [45]:
trans_arr=[]

def transcript_length(seq):
    return len(seq)

def fasta_to_transcript_length(fasta_file):
    global length
    with open(fasta_file) as f:
        seq = ''
        for line in f:
            if line.startswith('>'):
                if seq:
                    length = transcript_length(seq)
                    print(f'{length}\n')
                    trans_arr.append(length)
                    seq = ''
                header = line.strip()
            else:
                seq += line.strip()
        if seq:
            length = transcript_length(seq)
#             print(f'Sequence: {header}\nTranscript length: {length}\n')
            print(f'{length}\n')
            trans_arr.append(length)
        return length
fasta_to_transcript_length(filename)


2618

939

939

3465

3468

387

2557

1722

1860

2049

1671

1986

2191

1731

2757

2567

913

3176

2194

2455

698

3520

3035

2495

1040

885

667

787

657

637

7326

7394

7477

7408

1900

2429

1832

2010

2099

3214

2324

1097

842

836

740

554

575

579

2288

2307

568

2114

426

851

1083

727

705

1152

1012

1075

1184

1067

1153

811

878

946

959

1002

1933

2079

2095

728

2805

1036

2455

2260

2387

1057

1256

1047

1021

1028

1056

472

886

814

767

643

530

750

3050

2268

3475

2731

645

2679

923

3793

2280

582

1257

877

2629

2263

1862

2114

1832

1868

2571

1798

1618

1839

2004

1524

816

1056

659

579

849

750

800

1104

485

549

554

584

579

2154

783

3475

2926

3305

785

778

2231

2293

2001

2728

1072

798

753

875

3112

2059

2815

1598

1186

661

548

700

588

1049

2024

1632

1976

1506

876

3217

819

2147

4492

458

3864

525

4098

2114

2481

2612

2266

2330

830

1381

717

796

1284

4176

2124

303

2375

In [46]:
trans_arr

[2618,
 939,
 939,
 3465,
 3468,
 387,
 2557,
 1722,
 1860,
 2049,
 1671,
 1986,
 2191,
 1731,
 2757,
 2567,
 913,
 3176,
 2194,
 2455,
 698,
 3520,
 3035,
 2495,
 1040,
 885,
 667,
 787,
 657,
 637,
 7326,
 7394,
 7477,
 7408,
 1900,
 2429,
 1832,
 2010,
 2099,
 3214,
 2324,
 1097,
 842,
 836,
 740,
 554,
 575,
 579,
 2288,
 2307,
 568,
 2114,
 426,
 851,
 1083,
 727,
 705,
 1152,
 1012,
 1075,
 1184,
 1067,
 1153,
 811,
 878,
 946,
 959,
 1002,
 1933,
 2079,
 2095,
 728,
 2805,
 1036,
 2455,
 2260,
 2387,
 1057,
 1256,
 1047,
 1021,
 1028,
 1056,
 472,
 886,
 814,
 767,
 643,
 530,
 750,
 3050,
 2268,
 3475,
 2731,
 645,
 2679,
 923,
 3793,
 2280,
 582,
 1257,
 877,
 2629,
 2263,
 1862,
 2114,
 1832,
 1868,
 2571,
 1798,
 1618,
 1839,
 2004,
 1524,
 816,
 1056,
 659,
 579,
 849,
 750,
 800,
 1104,
 485,
 549,
 554,
 584,
 579,
 2154,
 783,
 3475,
 2926,
 3305,
 785,
 778,
 2231,
 2293,
 2001,
 2728,
 1072,
 798,
 753,
 875,
 3112,
 2059,
 2815,
 1598,
 1186,
 661,
 548,
 700,
 588,
 

# 7. MFE score

In [47]:
from Bio.Seq import Seq
from Bio.SeqUtils import MeltingTemp
from Bio import SeqIO

In [48]:
mfe_arr=[] 
for seq_record in SeqIO.parse(filename, "fasta"):
    rna_seq = Seq(str(seq_record.seq))

    mfe = MeltingTemp.Tm_Wallace(rna_seq.transcribe().reverse_complement_rna())
    mfe_arr.append(mfe)
    print(mfe)

7118.0
2742.0
2742.0
11776.0
11786.0
1272.0
8528.0
5802.0
6288.0
6928.0
5640.0
6716.0
7308.0
5878.0
8812.0
8470.0
3044.0
10454.0
7276.0
8158.0
2290.0
11656.0
10034.0
8298.0
3618.0
3076.0
2328.0
2572.0
2154.0
2092.0
24554.0
24774.0
25104.0
24884.0
6292.0
8048.0
6096.0
6690.0
6992.0
10694.0
7710.0
3590.0
2814.0
2776.0
2490.0
1844.0
1920.0
1894.0
7552.0
7612.0
1900.0
6880.0
1342.0
2870.0
3640.0
2408.0
2364.0
3910.0
3438.0
3640.0
4016.0
3606.0
3896.0
2744.0
2968.0
3190.0
3254.0
3396.0
6314.0
6808.0
6864.0
2332.0
9212.0
3506.0
7822.0
7210.0
7648.0
3372.0
3984.0
3362.0
3230.0
3296.0
3432.0
1508.0
2860.0
2636.0
2448.0
2140.0
1706.0
2446.0
10062.0
7466.0
11496.0
9094.0
2144.0
8904.0
3084.0
12562.0
7504.0
1884.0
4154.0
2948.0
8460.0
7282.0
6008.0
6794.0
5918.0
6042.0
8282.0
5796.0
5240.0
5934.0
6472.0
4886.0
2590.0
3402.0
2094.0
1856.0
2720.0
2400.0
2574.0
3500.0
1560.0
1788.0
1812.0
1884.0
1860.0
7200.0
2516.0
11532.0
9684.0
11070.0
2614.0
2560.0
7364.0
7616.0
6652.0
9050.0
3600.0
2656.0
2488.

In [49]:
mfe_arr

[7118.0,
 2742.0,
 2742.0,
 11776.0,
 11786.0,
 1272.0,
 8528.0,
 5802.0,
 6288.0,
 6928.0,
 5640.0,
 6716.0,
 7308.0,
 5878.0,
 8812.0,
 8470.0,
 3044.0,
 10454.0,
 7276.0,
 8158.0,
 2290.0,
 11656.0,
 10034.0,
 8298.0,
 3618.0,
 3076.0,
 2328.0,
 2572.0,
 2154.0,
 2092.0,
 24554.0,
 24774.0,
 25104.0,
 24884.0,
 6292.0,
 8048.0,
 6096.0,
 6690.0,
 6992.0,
 10694.0,
 7710.0,
 3590.0,
 2814.0,
 2776.0,
 2490.0,
 1844.0,
 1920.0,
 1894.0,
 7552.0,
 7612.0,
 1900.0,
 6880.0,
 1342.0,
 2870.0,
 3640.0,
 2408.0,
 2364.0,
 3910.0,
 3438.0,
 3640.0,
 4016.0,
 3606.0,
 3896.0,
 2744.0,
 2968.0,
 3190.0,
 3254.0,
 3396.0,
 6314.0,
 6808.0,
 6864.0,
 2332.0,
 9212.0,
 3506.0,
 7822.0,
 7210.0,
 7648.0,
 3372.0,
 3984.0,
 3362.0,
 3230.0,
 3296.0,
 3432.0,
 1508.0,
 2860.0,
 2636.0,
 2448.0,
 2140.0,
 1706.0,
 2446.0,
 10062.0,
 7466.0,
 11496.0,
 9094.0,
 2144.0,
 8904.0,
 3084.0,
 12562.0,
 7504.0,
 1884.0,
 4154.0,
 2948.0,
 8460.0,
 7282.0,
 6008.0,
 6794.0,
 5918.0,
 6042.0,
 8282.0,
 5796.

# 8. Protine Coding Potential

# 9. Conservation Score

# 10. Nucleotide Frequencies

# Data set and Correlation

In [50]:
import numpy as np
import pandas as pd

coding_is_one=[1]*len(gc_arr)
dataset = [orf_arr, gc_arr, trans_arr, cpg_arr, ficket_arr,coding_is_one]
Excluded =[mfe_arr,hexa_arr]


numpy_coding= np.array(dataset).T

df_coding = pd.DataFrame(data=numpy_coding, columns=["ORF Length", "GC Content", "Transcript Length",
                                            "CpG Island", "Ficket score","coding=1"])

df_coding


# ----------------------------------------------------------------------------------------------------------

# noncoding_is_zero=[0]*len(gc_arr)
# dataset = [orf_arr, gc_arr, trans_arr, cpg_arr, ficket_arr,noncoding_is_zero]
# Excluded =[mfe_arr,hexa_arr]

# numpy_ncoding= np.array(dataset).T

# df_ncoding = pd.DataFrame(data=numpy_ncoding, columns=["ORF Length", "GC Content", "Transcript Length",
#                                             "CpG Island", "Ficket score","coding=1"])

# df_ncoding

ORF Length  GC Content  Transcript Length  CpG Island  Ficket score  \
0          978.0   35.943468             2618.0        18.0      0.853194   
1          936.0   46.006390              939.0         8.0      0.405593   
2          936.0   46.006390              939.0         8.0      0.405593   
3         2532.0   69.927850             3465.0       302.0      1.376631   
4         2535.0   69.925029             3468.0       302.0      1.379372   
...          ...         ...                ...         ...           ...   
2427      2349.0   60.684050             2953.0        60.0      1.219299   
2428      2508.0   60.590095             2847.0        52.0      1.037350   
2429      1095.0   60.694444             1440.0        22.0      0.935463   
2430      2112.0   60.266160             3156.0        62.0      1.141730   
2431      2349.0   60.884211             2375.0        47.0      1.133400   

      coding=1  
0          1.0  
1          1.0  
2          1.0  
3          1.0  
4          1.0  
...        ...  
2427       1.0  
2428       1.0  
2429       1.0  
2430       1.0  
2431       1.0  

[2432 rows x 6 columns]

In [28]:
df_ncoding.corr()

ORF Length  GC Content  Transcript Length  CpG Island  \
ORF Length           1.000000    0.227663           0.424389    0.428375   
GC Content           0.227663    1.000000          -0.062143    0.469429   
Transcript Length    0.424389   -0.062143           1.000000    0.622534   
CpG Island           0.428375    0.469429           0.622534    1.000000   
Ficket score        -0.011326    0.120019          -0.156783   -0.055798   
coding=1                  NaN         NaN                NaN         NaN   

                   Ficket score  coding=1  
ORF Length            -0.011326       NaN  
GC Content             0.120019       NaN  
Transcript Length     -0.156783       NaN  
CpG Island            -0.055798       NaN  
Ficket score           1.000000       NaN  
coding=1                    NaN       NaN

In [51]:
df_coding.corr()

ORF Length  GC Content  Transcript Length  CpG Island  \
ORF Length           1.000000    0.003889           0.785937    0.740674   
GC Content           0.003889    1.000000          -0.181807    0.290269   
Transcript Length    0.785937   -0.181807           1.000000    0.742770   
CpG Island           0.740674    0.290269           0.742770    1.000000   
Ficket score         0.038624    0.103933          -0.152811   -0.024746   
coding=1                  NaN         NaN                NaN         NaN   

                   Ficket score  coding=1  
ORF Length             0.038624       NaN  
GC Content             0.103933       NaN  
Transcript Length     -0.152811       NaN  
CpG Island            -0.024746       NaN  
Ficket score           1.000000       NaN  
coding=1                    NaN       NaN

# Dataset Shuffled

In [52]:
import random

dataset_full=np.concatenate((numpy_ncoding,numpy_coding[5:314,:]))
np.random.shuffle(dataset_full)
dataset_full

array([[3.21000000e+02, 3.82049245e+01, 1.25900000e+03, 8.00000000e+00,
        1.00372068e+00, 0.00000000e+00],
       [2.04000000e+02, 4.15841584e+01, 1.01000000e+03, 1.60000000e+01,
        8.70002513e-01, 0.00000000e+00],
       [1.89000000e+02, 6.35220126e+01, 6.36000000e+02, 2.00000000e+01,
        1.26378373e+00, 0.00000000e+00],
       ...,
       [1.50000000e+01, 3.76237624e+01, 1.01000000e+02, 0.00000000e+00,
        1.27803672e+00, 0.00000000e+00],
       [4.50000000e+02, 4.43257677e+01, 7.49000000e+02, 7.00000000e+00,
        1.45680736e+00, 0.00000000e+00],
       [1.95000000e+02, 3.94678492e+01, 9.02000000e+02, 3.00000000e+00,
        1.25529264e+00, 0.00000000e+00]])

In [53]:
dataset_full.shape

(4904, 6)

In [54]:
d= dataset_full

d_pd = pd.DataFrame(data=d, columns=["ORF Length", "GC Content", "Transcript Length",
                                            "CpG Island", "Ficket score","coding=1"])

d_pd

ORF Length  GC Content  Transcript Length  CpG Island  Ficket score  \
0          321.0   38.204925             1259.0         8.0      1.003721   
1          204.0   41.584158             1010.0        16.0      0.870003   
2          189.0   63.522013              636.0        20.0      1.263784   
3           99.0   43.720930              645.0         4.0      1.744452   
4          213.0   53.539254              777.0        14.0      1.023420   
...          ...         ...                ...         ...           ...   
4899       204.0   42.629816             2388.0         8.0      1.117230   
4900       339.0   41.570881             2088.0        14.0      1.109056   
4901        15.0   37.623762              101.0         0.0      1.278037   
4902       450.0   44.325768              749.0         7.0      1.456807   
4903       195.0   39.467849              902.0         3.0      1.255293   

      coding=1  
0          0.0  
1          0.0  
2          0.0  
3          0.0  
4          0.0  
...        ...  
4899       0.0  
4900       0.0  
4901       0.0  
4902       0.0  
4903       0.0  

[4904 rows x 6 columns]

In [55]:
# dataset_full[:,-1]

# CSV file

In [56]:
np.savetxt("created_dummy_dataset_heeee.csv", dataset_full, delimiter=",", fmt='%d',
           header='ORF Length,GC Content,Transcript Length,CpG Island,Ficket score,coding=1', comments="")

# Delete this

In [1]:
# numpy_ncoding.shape

# numpy_coding[5:314,:].shape

# arr1 = np.array([[1,2,3],[4,5,6]])
# arr2 = np.array([[7,8,9],[10,11,12]])

# res = np.concatenate((arr1,arr2))
# print(res)

# # Create an array
# x = np.arange(10)
# print(x)
# print()
# # Shuffle the array
# np.random.shuffle(x)

# # Print the shuffled array
# print(x)

# Logistic Regression model

In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset = pd.read_csv("created_dummy_dataset_heeee.csv")

In [58]:
dataset

ORF Length  GC Content  Transcript Length  CpG Island  Ficket score  \
0            321          38               1259           8             1   
1            204          41               1010          16             0   
2            189          63                636          20             1   
3             99          43                645           4             1   
4            213          53                777          14             1   
...          ...         ...                ...         ...           ...   
4899         204          42               2388           8             1   
4900         339          41               2088          14             1   
4901          15          37                101           0             1   
4902         450          44                749           7             1   
4903         195          39                902           3             1   

      coding=1  
0            0  
1            0  
2            0  
3            0  
4            0  
...        ...  
4899         0  
4900         0  
4901         0  
4902         0  
4903         0  

[4904 rows x 6 columns]

In [59]:
# input
x = dataset.iloc[:, :-1].values
  
# output
y = dataset.iloc[:, -1].values


In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=0)

In [61]:
X_train
# X_train.shape

array([[ 297,   48, 1306,   24,    0],
       [ 264,   50, 1766,   44,    1],
       [ 132,   54,  867,   35,    1],
       ...,
       [  66,   44,  399,    6,    1],
       [ 675,   48, 1309,   16,    1],
       [ 231,   45, 1005,    8,    0]])

In [62]:
X_test
# X_test.shape

array([[ 165,   36,  397,    1,    0],
       [ 156,   41,  875,   12,    1],
       [ 207,   45, 1165,    3,    1],
       ...,
       [ 342,   61, 1039,   90,    1],
       [  36,   41,  213,    3,    1],
       [ 174,   48, 1011,   40,    0]])

In [63]:

from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train) 
X_test = sc_x.transform(X_test)
  
print (X_train[0:10, :])

[[ 0.03128585  0.02003049  0.0341132  -0.11412219 -1.19326606]
 [-0.06499184  0.27583657  0.46216766  0.41793691  0.61581579]
 [-0.45010261  0.78744872 -0.37439964  0.17851031  0.61581579]
 [ 1.75553178  0.02003049  1.13867982  1.21602555 -1.19326606]
 [-0.4938652  -0.74738774 -0.54096866 -0.4067547  -1.19326606]
 [ 0.18007864  0.53164265 -0.68799606 -0.11412219  0.61581579]
 [ 0.38138655  1.68276999  0.69573651  2.04071716  0.61581579]
 [-0.44135009 -1.89851509 -0.51584373 -0.67278425 -1.19326606]
 [-0.74768821 -1.00319382 -0.91412049 -0.59297538  0.61581579]
 [-0.19627961  1.17115784 -0.93087044 -0.45996061  0.61581579]]


In [64]:
X_train.shape

(3678, 5)

In [65]:

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [66]:

y_pred = classifier.predict(X_test)

# Evaluation Metrics

In [67]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[1141    7]
 [  32   46]]


In [68]:

from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.968189233278956


In [72]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)


Test set RMSE: 0.17835573083319764


# Random Forest