In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv("datasheet_ver2.csv")
dataset

ORF Length  GC Content  Transcript Length  CpG Island  Ficket score   
0            138.0   38.569425              713.0         5.0      1.172722  \
1            189.0   48.032787             1220.0        41.0      1.168862   
2            171.0   53.114754              610.0        23.0      0.949387   
3            537.0   41.805556              720.0        10.0      1.154088   
4           1218.0   47.773502             1819.0        33.0      0.880220   
...            ...         ...                ...         ...           ...   
116041       141.0   51.027811              827.0        33.0      1.316544   
116042       333.0   36.901654             1149.0        11.0      0.853603   
116043       225.0   51.943463             1415.0        28.0      1.095665   
116044       276.0   48.976608              684.0        19.0      1.473068   
116045       315.0   42.086753              853.0        14.0      0.983502   

         Coding Potential  
0                     0.0  
1                     0.0  
2                     0.0  
3                     1.0  
4                     1.0  
...                   ...  
116041                0.0  
116042                1.0  
116043                0.0  
116044                1.0  
116045                1.0  

[116046 rows x 6 columns]

In [4]:
# input
x = dataset.iloc[:, :-1].values
# output
y = dataset.iloc[:, -1].values

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)

X_train

array([[1.5000000e+02, 5.0996678e+01, 6.0200000e+02, 6.0000000e+00,
        8.7262800e-01],
       [8.1300000e+02, 6.2576271e+01, 1.4750000e+03, 7.5000000e+01,
        6.3329000e-01],
       [2.7000000e+02, 4.5770065e+01, 1.8440000e+03, 5.5000000e+01,
        8.6990700e-01],
       ...,
       [4.3800000e+02, 5.6365884e+01, 8.0900000e+02, 1.5000000e+01,
        9.4130200e-01],
       [3.3900000e+02, 4.3225806e+01, 1.5500000e+03, 1.3000000e+01,
        1.2447110e+00],
       [2.3700000e+02, 4.2393509e+01, 1.4790000e+03, 3.0000000e+01,
        1.2684710e+00]])

In [5]:
from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train) 
X_test = sc_x.transform(X_test)

X_train

array([[-0.45494006,  0.43394288, -0.56210964, -0.67501905, -0.71011803],
       [ 0.02276914,  1.95734521, -0.19788187,  0.64219202, -1.28004112],
       [-0.36847685, -0.2536663 , -0.04392993,  0.26039171, -0.7165974 ],
       ...,
       [-0.24742837,  1.14031148, -0.47574635, -0.50320891, -0.54658821],
       [-0.31876051, -0.58838706, -0.16659082, -0.54138894,  0.17590382],
       [-0.39225423, -0.69788341, -0.19621301, -0.21685868,  0.23248227]])

# Logistic Regression model

In [6]:
from sklearn.linear_model import LogisticRegression

lr_classifier = LogisticRegression(random_state = 0)
lr_classifier.fit(X_train, y_train)

y_pred = lr_classifier.predict(X_test)

In [14]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(lr_classifier, x, y, cv=5)
# print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [12]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[10779   837]
 [ 2412  9182]]


In [13]:
from sklearn.metrics import accuracy_score

print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.8600172339508833


In [10]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)


Test set RMSE: 0.37414270813302875


# Random Forest

In [33]:
from sklearn.ensemble import RandomForestClassifier

random_classifier = RandomForestClassifier(n_estimators=50, random_state=0)
random_classifier.fit(X_train, y_train)

y_pred = random_classifier.predict(X_test)

In [21]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(random_classifier, x, y, cv=5)
print("Random Forrest Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Logistic Regression Accuracy: 0.89 (+/- 0.00)


In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[10634   982]
 [ 1586 10008]]


In [23]:
from sklearn.metrics import accuracy_score

print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.8893580353295993


In [24]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)

Test set RMSE: 0.33262886926783836


# Naive Bayes

In [47]:
from sklearn.naive_bayes import GaussianNB

nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

y_pred = nb_classifier.predict(X_test)

In [48]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(nb_classifier, x, y, cv=5)
# print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [49]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[11089   527]
 [ 4284  7310]]


In [50]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.7927186557518311


In [51]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)

Test set RMSE: 0.45528160982865196


# Support Vector Machine

In [29]:
from sklearn.svm import SVC

svm_classifier = SVC(kernel='linear', random_state=0)
svm_classifier.fit(X_train, y_train)

y_pred = svm_classifier.predict(X_test)

In [ ]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(svm_classifier, x, y, cv=5)
# print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [30]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[13493  1006]
 [ 3012 11501]]


In [31]:
from sklearn.metrics import accuracy_score

print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.8615055838963188


In [32]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)

Test set RMSE: 0.37214837914960913
