In [20]:
filename="pcRNA.fa"
# filename="lncRNA.fa"

# 1. Fickett_Score

In [21]:
ficket_arr=[]
def calculate_fickett_score(seq):
    """
    Calculates the Fickett score for a given DNA sequence.
    """
    num_a = seq.count('A')
    num_c = seq.count('C')
    num_g = seq.count('G')
    num_t = seq.count('T')
    
    if num_a + num_c + num_g + num_t == 0:
        return 0
    
    freq_a = num_a / (num_a + num_c + num_g + num_t)
    freq_c = num_c / (num_a + num_c + num_g + num_t)
    freq_g = num_g / (num_a + num_c + num_g + num_t)
    freq_t = num_t / (num_a + num_c + num_g + num_t)
    
    r_y_ratio = (freq_a + freq_g) / (freq_c + freq_t)
    a_t_ratio = freq_a / freq_t
    gc_content = freq_g + freq_c
    fickett_score = (r_y_ratio * a_t_ratio) + gc_content - 0.5
    
    return fickett_score

def read_fasta_file(filename):
    """
    Reads a FASTA file and returns a list of (header, sequence) tuples.
    """
    sequences = []
    with open(filename, 'r') as f:
        header = ''
        sequence = ''
        for line in f:
            if line.startswith('>'):
                if header != '':
                    sequences.append((header, sequence))
                header = line.strip()[1:]
                sequence = ''
            else:
                sequence += line.strip().upper()
        if header != '':
            sequences.append((header, sequence))
    return sequences

sequences = read_fasta_file(filename)

for header, sequence in sequences:
    fickett_score = calculate_fickett_score(sequence)
#     print(f'{header}\tFickett score: {fickett_score:.4f}')
    print(f'{fickett_score:.4f}')
    ficket_arr.append(fickett_score)


0.8532
0.4056
0.4056
1.3766
1.3794
1.5629
1.4147
1.4418
1.3507
1.3286
1.4558
1.3747
1.3571
1.2466
1.3373
1.0550
1.1389
1.3875
1.2255
1.2258
0.9779
1.2586
1.2530
1.1979
1.4667
1.2504
1.1785
2.0380
1.7655
1.8933
1.0338
1.0381
1.0243
1.0199
1.2620
1.0502
1.1439
1.1888
1.1778
1.0540
0.8844
0.9062
1.1836
1.1704
1.1662
1.0367
1.0238
0.9691
1.4686
1.4478
1.3455
1.4178
1.0890
1.1528
1.0455
1.2561
1.0082
1.3122
1.3603
1.3832
1.4516
1.2233
1.2538
1.2711
1.2677
1.5475
1.4069
1.3709
1.4368
1.4129
1.3979
1.8620
0.9244
1.0207
0.9772
0.9517
0.9279
1.3271
1.3650
1.3041
1.2406
1.1764
1.1623
1.3381
1.0673
0.9720
1.0381
1.0502
1.3313
1.1288
1.1718
1.0902
1.0867
1.0902
1.3093
1.1425
1.0201
1.1467
1.4567
1.8570
1.1044
1.1763
1.1135
1.3332
1.3668
1.3964
1.3779
1.3175
1.1159
1.4227
1.4085
1.4186
1.3930
1.5804
1.8913
1.3232
1.4591
1.5355
1.1530
1.1862
1.2015
1.1220
1.2108
1.1377
0.9378
1.0651
0.5989
1.2404
1.2134
1.0339
1.3124
1.3326
1.4223
1.3306
0.9472
0.9182
0.9322
0.9150
1.5297
1.5766
1.6160
1.5423
1.1651

In [22]:
ficket_arr

[0.8531940607002142,
 0.40559335077900616,
 0.40559335077900616,
 1.3766312397724225,
 1.3793723118589545,
 1.5628703121726377,
 1.4147350591713244,
 1.4417953154872503,
 1.3507343396564233,
 1.3285655379322148,
 1.4557681106793148,
 1.3747426609925388,
 1.3571035729485734,
 1.246578249010614,
 1.3372791881143997,
 1.054982909033313,
 1.138866954500108,
 1.3874992017852592,
 1.225534625747068,
 1.2257769058839874,
 0.9778927455941706,
 1.2585980000005375,
 1.253034115893482,
 1.197948177465395,
 1.4666656752438898,
 1.2504119770463595,
 1.1784607696151925,
 2.037958171977043,
 1.7654829986257043,
 1.8933089626173922,
 1.0338355041854301,
 1.0380563345488534,
 1.0242686130512975,
 1.019898568349242,
 1.261955624355005,
 1.0501510871591209,
 1.1438921417347145,
 1.188783815674772,
 1.1778000580662817,
 1.0540137753701422,
 0.8843839957214017,
 0.906169394236771,
 1.1836433236274884,
 1.1704496829657294,
 1.1662231269212686,
 1.0366544372030195,
 1.0238025055268976,
 0.9690816997766174,
 

In [23]:
len(ficket_arr)

2432

# 2. CpG Islands

In [24]:
cpg_arr=[]

from Bio import SeqIO

def calculate_cpg_islands(seq):
    cpg_islands = []
    cpg_count = 0
    in_island = False
    
    for i in range(len(seq)-1):
        if seq[i:i+2].upper() == 'CG':
            cpg_count += 1
            if not in_island:
                in_island = True
        else:
            if cpg_count > 0:
                cpg_islands.append(cpg_count)
                cpg_count = 0
                in_island = False
    
    if cpg_count > 0:
        cpg_islands.append(cpg_count)
    
    return cpg_islands

# Open the FASTA file and loop over each record
for record in SeqIO.parse(filename, "fasta"):
    seq_id = record.id
    seq = record.seq
    
    # Calculate the number of CpG islands for this sequence
    cpg_islands = calculate_cpg_islands(seq)
    num_islands = len(cpg_islands)
    
    # Print the results
#     print(f'{seq_id}\t{num_islands}')
    print(f'\t{num_islands}')
    cpg_arr.append(num_islands)


	18
	8
	8
	302
	302
	29
	162
	123
	131
	141
	120
	137
	136
	110
	124
	199
	70
	145
	117
	131
	30
	152
	128
	124
	135
	114
	83
	50
	41
	37
	535
	540
	545
	540
	94
	139
	117
	127
	128
	181
	123
	73
	61
	69
	63
	24
	20
	30
	133
	135
	34
	99
	15
	62
	76
	35
	58
	75
	60
	63
	67
	69
	65
	54
	55
	58
	51
	61
	148
	166
	167
	44
	256
	85
	151
	147
	156
	70
	79
	79
	68
	73
	91
	38
	56
	54
	54
	66
	42
	53
	154
	114
	165
	148
	30
	145
	51
	258
	158
	34
	89
	79
	118
	109
	91
	102
	90
	92
	115
	90
	82
	103
	107
	86
	43
	58
	38
	33
	39
	37
	40
	51
	29
	27
	29
	19
	21
	135
	29
	181
	207
	271
	63
	59
	122
	157
	148
	181
	92
	59
	55
	70
	146
	95
	139
	103
	57
	53
	40
	32
	18
	35
	131
	48
	57
	117
	31
	139
	30
	216
	283
	31
	164
	23
	224
	143
	174
	178
	140
	143
	54
	123
	65
	52
	92
	142
	197
	266
	290
	292
	281
	291
	45
	301
	87
	273
	89
	302
	52
	260
	251
	228
	37
	118
	57
	118
	138
	126
	81
	68
	66
	32
	160
	148
	142
	125
	112
	135
	139
	138
	114
	246
	228
	146
	127
	121
	114
	126
	125
	128
	118
	25
	3

	146
	108
	104
	115
	116
	117
	101
	77
	100
	128
	98
	23
	22
	19
	15
	14
	15
	25
	26
	9
	124
	33
	16
	29
	10
	20
	20
	17
	18
	27
	25
	14
	14
	19
	15
	9
	86
	81
	93
	102
	116
	112
	81
	79
	79
	52
	45
	26
	160
	20
	19
	118
	25
	226
	230
	268
	296
	328
	235
	228
	118
	80
	32
	54
	79
	49
	79
	22
	19
	7
	14
	35
	107
	44
	12
	13
	13
	14
	9
	14
	13
	2
	101
	70
	33
	72
	61
	85
	59
	21
	75
	82
	33
	49
	29
	26
	35
	55
	18
	28
	28
	30
	30
	21
	26
	17
	55
	60
	60
	50
	58
	42
	41
	33
	42
	21
	41
	42
	35
	34
	31
	42
	42
	42
	34
	39
	57
	40
	37
	40
	41
	56
	35
	57
	40
	33
	24
	71
	37
	34
	29
	36
	73
	82
	78
	17
	22
	13
	43
	75
	53
	70
	31
	55
	9
	29
	93
	39
	60
	57
	67
	30
	36
	43
	40
	18
	18
	14
	88
	191
	122
	41
	6
	23
	12
	9
	9
	11
	10
	9
	8
	8
	24
	43
	29
	83
	23
	31
	28
	17
	29
	40
	32
	5
	10
	4
	3
	63
	53
	11
	10
	194
	159
	39
	151
	49
	78
	50
	43
	103
	27
	24
	11
	52
	15
	10
	51
	11
	19
	3
	77
	46
	23
	56
	47
	55
	123
	141
	123
	46
	59
	85
	35
	61
	33
	42
	36
	40
	29
	30
	24
	38
	37
	13
	116
	

In [25]:
cpg_arr

[18,
 8,
 8,
 302,
 302,
 29,
 162,
 123,
 131,
 141,
 120,
 137,
 136,
 110,
 124,
 199,
 70,
 145,
 117,
 131,
 30,
 152,
 128,
 124,
 135,
 114,
 83,
 50,
 41,
 37,
 535,
 540,
 545,
 540,
 94,
 139,
 117,
 127,
 128,
 181,
 123,
 73,
 61,
 69,
 63,
 24,
 20,
 30,
 133,
 135,
 34,
 99,
 15,
 62,
 76,
 35,
 58,
 75,
 60,
 63,
 67,
 69,
 65,
 54,
 55,
 58,
 51,
 61,
 148,
 166,
 167,
 44,
 256,
 85,
 151,
 147,
 156,
 70,
 79,
 79,
 68,
 73,
 91,
 38,
 56,
 54,
 54,
 66,
 42,
 53,
 154,
 114,
 165,
 148,
 30,
 145,
 51,
 258,
 158,
 34,
 89,
 79,
 118,
 109,
 91,
 102,
 90,
 92,
 115,
 90,
 82,
 103,
 107,
 86,
 43,
 58,
 38,
 33,
 39,
 37,
 40,
 51,
 29,
 27,
 29,
 19,
 21,
 135,
 29,
 181,
 207,
 271,
 63,
 59,
 122,
 157,
 148,
 181,
 92,
 59,
 55,
 70,
 146,
 95,
 139,
 103,
 57,
 53,
 40,
 32,
 18,
 35,
 131,
 48,
 57,
 117,
 31,
 139,
 30,
 216,
 283,
 31,
 164,
 23,
 224,
 143,
 174,
 178,
 140,
 143,
 54,
 123,
 65,
 52,
 92,
 142,
 197,
 266,
 290,
 292,
 281,
 291,
 45,
 301

# 3. GC_Content

In [26]:
gc_arr=[]

def gc_content(seq):
    gc_count = seq.count('G') + seq.count('C')
    total_count = len(seq)
    return (gc_count / total_count) * 100

def fasta_to_gc_content(fasta_file):
    with open(fasta_file) as f:
        seq = ''
        for line in f:
            if line.startswith('>'):
                if seq:
                    gc = gc_content(seq)
                    print(f'{gc:.2f}%\n')
                    gc_arr.append(gc)
                    seq = ''
                header = line.strip()
            else:
                seq += line.strip()
        if seq:
            gc = gc_content(seq)
#             print(f'Sequence: {header}\nGC content: {gc:.2f}%\n')
            print(f'{gc:.2f}%\n')
            gc_arr.append(gc)

fasta_to_gc_content(filename)


35.94%

46.01%

46.01%

69.93%

69.93%

64.34%

66.76%

68.47%

69.03%

69.06%

68.76%

69.08%

66.77%

69.79%

59.81%

64.98%

66.70%

64.58%

65.82%

66.15%

64.04%

65.57%

65.30%

66.29%

73.94%

73.79%

74.51%

63.41%

63.93%

64.21%

67.58%

67.53%

67.87%

67.95%

65.58%

65.66%

66.38%

66.42%

66.56%

66.37%

65.88%

63.63%

67.10%

66.03%

68.24%

66.43%

66.96%

63.56%

65.03%

64.98%

67.25%

62.72%

57.51%

68.63%

68.05%

65.61%

67.66%

69.70%

69.86%

69.30%

69.59%

68.98%

68.95%

69.17%

69.02%

68.60%

69.66%

69.46%

63.32%

63.73%

63.82%

60.16%

64.21%

69.21%

59.31%

59.51%

60.20%

59.51%

58.60%

60.55%

58.18%

60.31%

62.50%

59.75%

61.40%

61.92%

59.58%

66.41%

60.94%

63.07%

64.95%

64.59%

65.41%

66.50%

66.20%

66.18%

67.06%

65.59%

64.56%

61.86%

65.23%

68.07%

60.90%

60.89%

61.33%

60.69%

61.52%

61.72%

61.07%

61.18%

61.93%

61.34%

61.48%

60.30%

58.70%

61.08%

58.88%

60.28%

60.19%

60.00%

60.88%

58.51%

60.82%

62.84%

63.54%



In [27]:
gc_arr

[35.94346829640948,
 46.00638977635783,
 46.00638977635783,
 69.92784992784993,
 69.92502883506344,
 64.34108527131784,
 66.75791943684006,
 68.46689895470384,
 69.03225806451613,
 69.05807711078576,
 68.76122082585279,
 69.08358509566969,
 66.77316293929712,
 69.78625072212594,
 59.8113891911498,
 64.97857421114142,
 66.70317634173057,
 64.57808564231739,
 65.8158614402917,
 66.15071283095723,
 64.04011461318052,
 65.56818181818181,
 65.30477759472817,
 66.29258517034067,
 73.9423076923077,
 73.78531073446327,
 74.5127436281859,
 63.40533672172808,
 63.926940639269404,
 64.2072213500785,
 67.58121758121757,
 67.52772518258047,
 67.874816102715,
 67.95356371490281,
 65.57894736842104,
 65.66488266776452,
 66.37554585152839,
 66.4179104477612,
 66.55550262029539,
 66.3658991910392,
 65.87779690189329,
 63.62807657247037,
 67.10213776722091,
 66.02870813397129,
 68.24324324324324,
 66.4259927797834,
 66.95652173913044,
 63.55785837651122,
 65.03496503496503,
 64.97615951452103,
 67.25352

# 4. Hexamer Score

In [28]:
hexa_arr=[]

from collections import Counter

def hexamer_score(seq):
    hexamers = [seq[i:i+6] for i in range(len(seq)-5)]
    counts = Counter(hexamers)
    score = sum(counts.values())
    return score

def fasta_to_hexamer_score(fasta_file):
    with open(fasta_file) as f:
        seq = ''
        for line in f:
            if line.startswith('>'):
                if seq:
                    score = hexamer_score(seq)
                    print(f'{score}\n')
                    hexa_arr.append(score)
                    seq = ''
                header = line.strip()
            else:
                seq += line.strip()
        if seq:
            score = hexamer_score(seq)
#             print(f'Sequence: {header}\nHexamer score: {score}\n')
            print(f'{score}\n')
            hexa_arr.append(score)

fasta_to_hexamer_score(filename)


2613

934

934

3460

3463

382

2552

1717

1855

2044

1666

1981

2186

1726

2752

2562

908

3171

2189

2450

693

3515

3030

2490

1035

880

662

782

652

632

7321

7389

7472

7403

1895

2424

1827

2005

2094

3209

2319

1092

837

831

735

549

570

574

2283

2302

563

2109

421

846

1078

722

700

1147

1007

1070

1179

1062

1148

806

873

941

954

997

1928

2074

2090

723

2800

1031

2450

2255

2382

1052

1251

1042

1016

1023

1051

467

881

809

762

638

525

745

3045

2263

3470

2726

640

2674

918

3788

2275

577

1252

872

2624

2258

1857

2109

1827

1863

2566

1793

1613

1834

1999

1519

811

1051

654

574

844

745

795

1099

480

544

549

579

574

2149

778

3470

2921

3300

780

773

2226

2288

1996

2723

1067

793

748

870

3107

2054

2810

1593

1181

656

543

695

583

1044

2019

1627

1971

1501

871

3212

814

2142

4487

453

3859

520

4093

2109

2476

2607

2261

2325

825

1376

712

791

1279

4171

2119

3029

In [29]:
hexa_arr

[2613,
 934,
 934,
 3460,
 3463,
 382,
 2552,
 1717,
 1855,
 2044,
 1666,
 1981,
 2186,
 1726,
 2752,
 2562,
 908,
 3171,
 2189,
 2450,
 693,
 3515,
 3030,
 2490,
 1035,
 880,
 662,
 782,
 652,
 632,
 7321,
 7389,
 7472,
 7403,
 1895,
 2424,
 1827,
 2005,
 2094,
 3209,
 2319,
 1092,
 837,
 831,
 735,
 549,
 570,
 574,
 2283,
 2302,
 563,
 2109,
 421,
 846,
 1078,
 722,
 700,
 1147,
 1007,
 1070,
 1179,
 1062,
 1148,
 806,
 873,
 941,
 954,
 997,
 1928,
 2074,
 2090,
 723,
 2800,
 1031,
 2450,
 2255,
 2382,
 1052,
 1251,
 1042,
 1016,
 1023,
 1051,
 467,
 881,
 809,
 762,
 638,
 525,
 745,
 3045,
 2263,
 3470,
 2726,
 640,
 2674,
 918,
 3788,
 2275,
 577,
 1252,
 872,
 2624,
 2258,
 1857,
 2109,
 1827,
 1863,
 2566,
 1793,
 1613,
 1834,
 1999,
 1519,
 811,
 1051,
 654,
 574,
 844,
 745,
 795,
 1099,
 480,
 544,
 549,
 579,
 574,
 2149,
 778,
 3470,
 2921,
 3300,
 780,
 773,
 2226,
 2288,
 1996,
 2723,
 1067,
 793,
 748,
 870,
 3107,
 2054,
 2810,
 1593,
 1181,
 656,
 543,
 695,
 583,
 1

# 5. ORF_Length

In [30]:
orf_arr=[]

def read_fasta_file(filename):
    """
    Reads a FASTA file and returns a list of (header, sequence) tuples.
    """
    sequences = []
    with open(filename, 'r') as f:
        header = ''
        sequence = ''
        for line in f:
            if line.startswith('>'):
                if header != '':
                    sequences.append((header, sequence))
                header = line.strip()[1:]
                sequence = ''
            else:
                sequence += line.strip().upper()
        if header != '':
            sequences.append((header, sequence))
    return sequences

def find_longest_orf(sequence):
    """
    Finds the longest ORF in a given DNA sequence.
    """
    longest_orf_length = 0
    for frame in range(3):
        for pos in range(frame, len(sequence)-2, 3):
            codon = sequence[pos:pos+3]
            if codon == 'ATG':
                orf_length = 0
                for pos2 in range(pos, len(sequence)-2, 3):
                    codon2 = sequence[pos2:pos2+3]
                    if codon2 in ('TAA', 'TAG', 'TGA'):
                        break
                    else:
                        orf_length += 3
                if orf_length > longest_orf_length:
                    longest_orf_length = orf_length
    return longest_orf_length

sequences = read_fasta_file(filename)

for header, sequence in sequences:
    orf_length = find_longest_orf(sequence)
#     print(f'{header}\tORF length: {orf_length}')
    print(f'{orf_length}')
    orf_arr.append(orf_length)

978
936
936
2532
2535
327
2043
1719
1857
2046
1668
1983
1752
1587
2247
1926
384
1833
1728
1989
387
2370
2028
2370
741
663
567
471
429
495
6135
6204
5889
5820
747
1140
594
567
390
762
1032
594
669
309
354
222
210
147
2019
2019
435
1212
243
765
723
507
702
894
1005
831
1065
609
909
567
759
702
933
975
1086
1044
762
720
987
906
672
777
621
621
621
777
825
558
588
180
513
237
300
303
213
129
2406
1680
1914
1914
417
2112
840
2502
2277
402
909
375
1818
1713
1506
1800
1506
1026
1818
1497
1281
1734
1713
834
519
1032
327
453
714
627
747
867
420
174
501
174
330
663
351
2556
2010
2085
480
750
1023
1326
1350
1299
597
597
597
597
1560
894
894
894
678
540
261
447
117
465
1197
261
522
1197
522
489
501
699
1335
444
1233
393
1944
1626
1758
1902
1227
1521
726
519
519
336
582
459
678
2562
2997
3039
2844
3027
342
2448
252
2259
525
2907
444
2757
1185
2457
267
384
498
1170
714
1158
513
510
459
228
2346
2385
2244
1695
1578
2316
2349
2355
738
1215
1215
2340
2238
2238
1260
2337
2310
2349
1221
453
111
1338
1338

1632
1764
1923
1626
2325
2025
2592
2361
2298
1821
2421
2244
2592
1443
2346
2160
2523
2484
2040
831
1176
1098
375
654
921
921
1482
1113
1134
480
1119
891
498
4338
4308
4299
4320
168
1488
786
1326
1152
2832
3558
3567
3564
3324
2562
3486
3672
3381
156
669
534
378
612
282
747
387
288
621
408
378
1071
507
438
699
537
480
789
723
723
750
399
267
396
1392
1377
1365
1377
1308
1401
1086
849
1275
1275
1167
852
4812
387
498
2898
411
4500
4497
4752
4398
4755
4653
4662
2526
1521
180
2088
3648
1917
3609
435
291
261
399
501
501
501
408
426
219
198
207
189
66
63
1329
1212
576
1476
879
1608
933
927
1638
1638
600
723
387
345
1398
1638
1047
288
492
492
540
492
420
201
975
975
975
831
975
576
1086
924
969
498
747
972
576
1071
543
876
756
975
348
810
1314
1065
1041
747
651
1221
882
1149
897
825
804
390
423
582
489
357
1374
1701
1527
447
411
501
855
1617
747
1446
633
585
105
804
381
177
1290
1284
1422
1005
1122
1341
1059
267
531
468
1536
1485
1323
1020
228
501
243
480
207
393
228
408
330
330
210
1272
321
12

In [31]:
orf_arr

[978,
 936,
 936,
 2532,
 2535,
 327,
 2043,
 1719,
 1857,
 2046,
 1668,
 1983,
 1752,
 1587,
 2247,
 1926,
 384,
 1833,
 1728,
 1989,
 387,
 2370,
 2028,
 2370,
 741,
 663,
 567,
 471,
 429,
 495,
 6135,
 6204,
 5889,
 5820,
 747,
 1140,
 594,
 567,
 390,
 762,
 1032,
 594,
 669,
 309,
 354,
 222,
 210,
 147,
 2019,
 2019,
 435,
 1212,
 243,
 765,
 723,
 507,
 702,
 894,
 1005,
 831,
 1065,
 609,
 909,
 567,
 759,
 702,
 933,
 975,
 1086,
 1044,
 762,
 720,
 987,
 906,
 672,
 777,
 621,
 621,
 621,
 777,
 825,
 558,
 588,
 180,
 513,
 237,
 300,
 303,
 213,
 129,
 2406,
 1680,
 1914,
 1914,
 417,
 2112,
 840,
 2502,
 2277,
 402,
 909,
 375,
 1818,
 1713,
 1506,
 1800,
 1506,
 1026,
 1818,
 1497,
 1281,
 1734,
 1713,
 834,
 519,
 1032,
 327,
 453,
 714,
 627,
 747,
 867,
 420,
 174,
 501,
 174,
 330,
 663,
 351,
 2556,
 2010,
 2085,
 480,
 750,
 1023,
 1326,
 1350,
 1299,
 597,
 597,
 597,
 597,
 1560,
 894,
 894,
 894,
 678,
 540,
 261,
 447,
 117,
 465,
 1197,
 261,
 522,
 1197,
 522

# 6. Transcript_length

In [32]:
trans_arr=[]

def transcript_length(seq):
    return len(seq)

def fasta_to_transcript_length(fasta_file):
    global length
    with open(fasta_file) as f:
        seq = ''
        for line in f:
            if line.startswith('>'):
                if seq:
                    length = transcript_length(seq)
                    print(f'{length}\n')
                    trans_arr.append(length)
                    seq = ''
                header = line.strip()
            else:
                seq += line.strip()
        if seq:
            length = transcript_length(seq)
#             print(f'Sequence: {header}\nTranscript length: {length}\n')
            print(f'{length}\n')
            trans_arr.append(length)
        return length
fasta_to_transcript_length(filename)


2618

939

939

3465

3468

387

2557

1722

1860

2049

1671

1986

2191

1731

2757

2567

913

3176

2194

2455

698

3520

3035

2495

1040

885

667

787

657

637

7326

7394

7477

7408

1900

2429

1832

2010

2099

3214

2324

1097

842

836

740

554

575

579

2288

2307

568

2114

426

851

1083

727

705

1152

1012

1075

1184

1067

1153

811

878

946

959

1002

1933

2079

2095

728

2805

1036

2455

2260

2387

1057

1256

1047

1021

1028

1056

472

886

814

767

643

530

750

3050

2268

3475

2731

645

2679

923

3793

2280

582

1257

877

2629

2263

1862

2114

1832

1868

2571

1798

1618

1839

2004

1524

816

1056

659

579

849

750

800

1104

485

549

554

584

579

2154

783

3475

2926

3305

785

778

2231

2293

2001

2728

1072

798

753

875

3112

2059

2815

1598

1186

661

548

700

588

1049

2024

1632

1976

1506

876

3217

819

2147

4492

458

3864

525

4098

2114

2481

2612

2266

2330

830

1381

717

796

1284

4176

2124

303

2375

In [33]:
trans_arr

[2618,
 939,
 939,
 3465,
 3468,
 387,
 2557,
 1722,
 1860,
 2049,
 1671,
 1986,
 2191,
 1731,
 2757,
 2567,
 913,
 3176,
 2194,
 2455,
 698,
 3520,
 3035,
 2495,
 1040,
 885,
 667,
 787,
 657,
 637,
 7326,
 7394,
 7477,
 7408,
 1900,
 2429,
 1832,
 2010,
 2099,
 3214,
 2324,
 1097,
 842,
 836,
 740,
 554,
 575,
 579,
 2288,
 2307,
 568,
 2114,
 426,
 851,
 1083,
 727,
 705,
 1152,
 1012,
 1075,
 1184,
 1067,
 1153,
 811,
 878,
 946,
 959,
 1002,
 1933,
 2079,
 2095,
 728,
 2805,
 1036,
 2455,
 2260,
 2387,
 1057,
 1256,
 1047,
 1021,
 1028,
 1056,
 472,
 886,
 814,
 767,
 643,
 530,
 750,
 3050,
 2268,
 3475,
 2731,
 645,
 2679,
 923,
 3793,
 2280,
 582,
 1257,
 877,
 2629,
 2263,
 1862,
 2114,
 1832,
 1868,
 2571,
 1798,
 1618,
 1839,
 2004,
 1524,
 816,
 1056,
 659,
 579,
 849,
 750,
 800,
 1104,
 485,
 549,
 554,
 584,
 579,
 2154,
 783,
 3475,
 2926,
 3305,
 785,
 778,
 2231,
 2293,
 2001,
 2728,
 1072,
 798,
 753,
 875,
 3112,
 2059,
 2815,
 1598,
 1186,
 661,
 548,
 700,
 588,
 

# 7. MFE score

In [34]:
from Bio.Seq import Seq
from Bio.SeqUtils import MeltingTemp
from Bio import SeqIO

In [35]:
mfe_arr=[] 
for seq_record in SeqIO.parse(filename, "fasta"):
    rna_seq = Seq(str(seq_record.seq))

    mfe = MeltingTemp.Tm_Wallace(rna_seq.transcribe().reverse_complement_rna())
    mfe_arr.append(mfe)
    print(mfe)

7118.0
2742.0
2742.0
11776.0
11786.0
1272.0
8528.0
5802.0
6288.0
6928.0
5640.0
6716.0
7308.0
5878.0
8812.0
8470.0
3044.0
10454.0
7276.0
8158.0
2290.0
11656.0
10034.0
8298.0
3618.0
3076.0
2328.0
2572.0
2154.0
2092.0
24554.0
24774.0
25104.0
24884.0
6292.0
8048.0
6096.0
6690.0
6992.0
10694.0
7710.0
3590.0
2814.0
2776.0
2490.0
1844.0
1920.0
1894.0
7552.0
7612.0
1900.0
6880.0
1342.0
2870.0
3640.0
2408.0
2364.0
3910.0
3438.0
3640.0
4016.0
3606.0
3896.0
2744.0
2968.0
3190.0
3254.0
3396.0
6314.0
6808.0
6864.0
2332.0
9212.0
3506.0
7822.0
7210.0
7648.0
3372.0
3984.0
3362.0
3230.0
3296.0
3432.0
1508.0
2860.0
2636.0
2448.0
2140.0
1706.0
2446.0
10062.0
7466.0
11496.0
9094.0
2144.0
8904.0
3084.0
12562.0
7504.0
1884.0
4154.0
2948.0
8460.0
7282.0
6008.0
6794.0
5918.0
6042.0
8282.0
5796.0
5240.0
5934.0
6472.0
4886.0
2590.0
3402.0
2094.0
1856.0
2720.0
2400.0
2574.0
3500.0
1560.0
1788.0
1812.0
1884.0
1860.0
7200.0
2516.0
11532.0
9684.0
11070.0
2614.0
2560.0
7364.0
7616.0
6652.0
9050.0
3600.0
2656.0
2488.

In [36]:
mfe_arr

[7118.0,
 2742.0,
 2742.0,
 11776.0,
 11786.0,
 1272.0,
 8528.0,
 5802.0,
 6288.0,
 6928.0,
 5640.0,
 6716.0,
 7308.0,
 5878.0,
 8812.0,
 8470.0,
 3044.0,
 10454.0,
 7276.0,
 8158.0,
 2290.0,
 11656.0,
 10034.0,
 8298.0,
 3618.0,
 3076.0,
 2328.0,
 2572.0,
 2154.0,
 2092.0,
 24554.0,
 24774.0,
 25104.0,
 24884.0,
 6292.0,
 8048.0,
 6096.0,
 6690.0,
 6992.0,
 10694.0,
 7710.0,
 3590.0,
 2814.0,
 2776.0,
 2490.0,
 1844.0,
 1920.0,
 1894.0,
 7552.0,
 7612.0,
 1900.0,
 6880.0,
 1342.0,
 2870.0,
 3640.0,
 2408.0,
 2364.0,
 3910.0,
 3438.0,
 3640.0,
 4016.0,
 3606.0,
 3896.0,
 2744.0,
 2968.0,
 3190.0,
 3254.0,
 3396.0,
 6314.0,
 6808.0,
 6864.0,
 2332.0,
 9212.0,
 3506.0,
 7822.0,
 7210.0,
 7648.0,
 3372.0,
 3984.0,
 3362.0,
 3230.0,
 3296.0,
 3432.0,
 1508.0,
 2860.0,
 2636.0,
 2448.0,
 2140.0,
 1706.0,
 2446.0,
 10062.0,
 7466.0,
 11496.0,
 9094.0,
 2144.0,
 8904.0,
 3084.0,
 12562.0,
 7504.0,
 1884.0,
 4154.0,
 2948.0,
 8460.0,
 7282.0,
 6008.0,
 6794.0,
 5918.0,
 6042.0,
 8282.0,
 5796.

# 8. Protine Coding Potential

# 9. Conservation Score

# 10. Nucleotide Frequencies

# Data set and Correlation

In [37]:
import numpy as np
import pandas as pd

coding_is_one=[1]*len(gc_arr)
dataset = [orf_arr, gc_arr, trans_arr, cpg_arr, ficket_arr,coding_is_one]
Excluded =[mfe_arr,hexa_arr]


numpy_coding= np.array(dataset).T

df_coding = pd.DataFrame(data=numpy_coding, columns=["ORF Length", "GC Content", "Transcript Length",
                                            "CpG Island", "Ficket score","coding=1"])

df_coding


# ----------------------------------------------------------------------------------------------------------

# noncoding_is_zero=[0]*len(gc_arr)
# dataset = [orf_arr, gc_arr, trans_arr, cpg_arr, ficket_arr,noncoding_is_zero]
# Excluded =[mfe_arr,hexa_arr]

# numpy_ncoding= np.array(dataset).T

# df_ncoding = pd.DataFrame(data=numpy_ncoding, columns=["ORF Length", "GC Content", "Transcript Length",
#                                             "CpG Island", "Ficket score","coding=1"])

# df_ncoding

ORF Length  GC Content  Transcript Length  CpG Island  Ficket score  \
0          978.0   35.943468             2618.0        18.0      0.853194   
1          936.0   46.006390              939.0         8.0      0.405593   
2          936.0   46.006390              939.0         8.0      0.405593   
3         2532.0   69.927850             3465.0       302.0      1.376631   
4         2535.0   69.925029             3468.0       302.0      1.379372   
...          ...         ...                ...         ...           ...   
2427      2349.0   60.684050             2953.0        60.0      1.219299   
2428      2508.0   60.590095             2847.0        52.0      1.037350   
2429      1095.0   60.694444             1440.0        22.0      0.935463   
2430      2112.0   60.266160             3156.0        62.0      1.141730   
2431      2349.0   60.884211             2375.0        47.0      1.133400   

      coding=1  
0          1.0  
1          1.0  
2          1.0  
3          1.0  
4          1.0  
...        ...  
2427       1.0  
2428       1.0  
2429       1.0  
2430       1.0  
2431       1.0  

[2432 rows x 6 columns]

In [19]:
df_ncoding.corr()

ORF Length  GC Content  Transcript Length  CpG Island  \
ORF Length           1.000000    0.227663           0.424389    0.428375   
GC Content           0.227663    1.000000          -0.062143    0.469429   
Transcript Length    0.424389   -0.062143           1.000000    0.622534   
CpG Island           0.428375    0.469429           0.622534    1.000000   
Ficket score        -0.011326    0.120019          -0.156783   -0.055798   
coding=1                  NaN         NaN                NaN         NaN   

                   Ficket score  coding=1  
ORF Length            -0.011326       NaN  
GC Content             0.120019       NaN  
Transcript Length     -0.156783       NaN  
CpG Island            -0.055798       NaN  
Ficket score           1.000000       NaN  
coding=1                    NaN       NaN

In [38]:
df_coding.corr()

ORF Length  GC Content  Transcript Length  CpG Island  \
ORF Length           1.000000    0.003889           0.785937    0.740674   
GC Content           0.003889    1.000000          -0.181807    0.290269   
Transcript Length    0.785937   -0.181807           1.000000    0.742770   
CpG Island           0.740674    0.290269           0.742770    1.000000   
Ficket score         0.038624    0.103933          -0.152811   -0.024746   
coding=1                  NaN         NaN                NaN         NaN   

                   Ficket score  coding=1  
ORF Length             0.038624       NaN  
GC Content             0.103933       NaN  
Transcript Length     -0.152811       NaN  
CpG Island            -0.024746       NaN  
Ficket score           1.000000       NaN  
coding=1                    NaN       NaN

# Dataset Shuffled

In [39]:
import random

dataset_full=np.concatenate((numpy_ncoding,numpy_coding[5:314,:]))
np.random.shuffle(dataset_full)
dataset_full

array([[1.98000000e+02, 4.30868167e+01, 6.22000000e+02, 5.00000000e+00,
        1.31003483e+00, 0.00000000e+00],
       [2.19000000e+02, 5.79804560e+01, 6.14000000e+02, 3.60000000e+01,
        1.63693375e+00, 1.00000000e+00],
       [1.33200000e+03, 3.83526049e+01, 7.69700000e+03, 6.90000000e+01,
        1.82686038e+00, 0.00000000e+00],
       ...,
       [2.19000000e+02, 4.28391960e+01, 7.96000000e+02, 8.00000000e+00,
        8.67988699e-01, 0.00000000e+00],
       [1.68000000e+02, 4.60280374e+01, 4.28000000e+02, 1.20000000e+01,
        1.83670980e+00, 0.00000000e+00],
       [1.71000000e+02, 4.39060206e+01, 6.81000000e+02, 6.00000000e+00,
        1.41578158e+00, 0.00000000e+00]])

In [40]:
dataset_full.shape

(4904, 6)

In [41]:
d= dataset_full

d_pd = pd.DataFrame(data=d, columns=["ORF Length", "GC Content", "Transcript Length",
                                            "CpG Island", "Ficket score","coding=1"])

d_pd

ORF Length  GC Content  Transcript Length  CpG Island  Ficket score  \
0          198.0   43.086817              622.0         5.0      1.310035   
1          219.0   57.980456              614.0        36.0      1.636934   
2         1332.0   38.352605             7697.0        69.0      1.826860   
3          375.0   68.072976              877.0        79.0      1.176305   
4          213.0   50.136986              365.0         7.0      2.023268   
...          ...         ...                ...         ...           ...   
4899       129.0   41.081871              684.0         5.0      0.803381   
4900       108.0   46.355685              686.0         3.0      0.679810   
4901       219.0   42.839196              796.0         8.0      0.867989   
4902       168.0   46.028037              428.0        12.0      1.836710   
4903       171.0   43.906021              681.0         6.0      1.415782   

      coding=1  
0          0.0  
1          1.0  
2          0.0  
3          1.0  
4          0.0  
...        ...  
4899       0.0  
4900       0.0  
4901       0.0  
4902       0.0  
4903       0.0  

[4904 rows x 6 columns]

In [42]:
# dataset_full[:,-1]

# CSV file

In [43]:
np.savetxt("created_dummy_dataset_heeee.csv", dataset_full, delimiter=",", fmt='%d',
           header='ORF Length,GC Content,Transcript Length,CpG Island,Ficket score,coding=1', comments="")

# Logistic Regression model

In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset = pd.read_csv("created_dummy_dataset_heeee.csv")

In [46]:
dataset

ORF Length  GC Content  Transcript Length  CpG Island  Ficket score  \
0            198          43                622           5             1   
1            219          57                614          36             1   
2           1332          38               7697          69             1   
3            375          68                877          79             1   
4            213          50                365           7             2   
...          ...         ...                ...         ...           ...   
4899         129          41                684           5             0   
4900         108          46                686           3             0   
4901         219          42                796           8             0   
4902         168          46                428          12             1   
4903         171          43                681           6             1   

      coding=1  
0            0  
1            1  
2            0  
3            1  
4            0  
...        ...  
4899         0  
4900         0  
4901         0  
4902         0  
4903         0  

[4904 rows x 6 columns]

In [47]:
# input
x = dataset.iloc[:, :-1].values
  
# output
y = dataset.iloc[:, -1].values


In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=0)

In [49]:
X_train
# X_train.shape

array([[ 237,   45,  353,   13,    1],
       [ 294,   44,  714,    9,    1],
       [2337,   56, 2446,  126,    3],
       ...,
       [ 165,   39,  642,    6,    0],
       [ 198,   43,  601,   16,    1],
       [ 471,   66,  664,   51,    1]])

In [50]:
X_test
# X_test.shape

array([[ 105,   36,  459,    3,    1],
       [ 114,   39, 1051,   11,    1],
       [ 195,   44,  890,   11,    0],
       ...,
       [ 297,   55, 1306,   57,    1],
       [ 105,   43, 1306,   30,    1],
       [1926,   64, 2567,  199,    1]])

In [51]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train) 
X_test = sc_x.transform(X_test)
  
print (X_train[0:10, :])

[[-0.13182556 -0.36520137 -0.89152663 -0.3987294   0.61879303]
 [ 0.03017057 -0.49467993 -0.53249401 -0.50788862  0.61879303]
 [ 5.83645271  1.05906285  1.1900669   2.68501839  4.23710906]
 [-0.45581781  0.54114859 -0.61404713 -0.50788862  0.61879303]
 [ 2.58800411  0.92958428  0.13484916  0.25622588  0.61879303]
 [-0.47287003  0.28219146 -0.4668537  -0.58975803  0.61879303]
 [-0.21708668 -1.01259419  0.38647036 -0.42601921 -1.19036498]
 [-0.54960504  0.02323433 -0.68167654 -0.58975803  0.61879303]
 [-0.14035167  0.02323433 -0.08096823 -0.28957019 -1.19036498]
 [-0.01245999 -1.14207276 -0.42607714 -0.28957019 -1.19036498]]


In [52]:
X_train.shape

(3678, 5)

In [53]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

# Evaluation Metrics

In [54]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[1130   13]
 [  34   49]]


In [55]:

from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.9616639477977161


In [56]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)


Test set RMSE: 0.19579594531624972


# Random Forest

In [60]:
from sklearn.ensemble import RandomForestClassifier

random_classifier = RandomForestClassifier(n_estimators=50, random_state=0)
random_classifier.fit(X_train, y_train)

y_pred = random_classifier.predict(X_test)

In [61]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[1129   14]
 [  16   67]]


In [62]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.9755301794453507


In [63]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)


Test set RMSE: 0.15642832401662196


# Support Vector Machine

In [69]:
from sklearn.svm import SVC

svm_classifier = SVC(kernel='linear', random_state=0)
svm_classifier.fit(X_train, y_train)

y_pred = svm_classifier.predict(X_test)

In [70]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[1131   12]
 [  34   49]]


In [71]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.9624796084828712


In [72]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)

Test set RMSE: 0.19370181082563187


# Naive Bayes

In [65]:
from sklearn.naive_bayes import GaussianNB

nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

y_pred = nb_classifier.predict(X_test)

In [66]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[1096   47]
 [  23   60]]


In [67]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.9429037520391517


In [68]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)

Test set RMSE: 0.23894821188041623


# Pickle formation

In [73]:
import pickle

with open('lr_model.pkl','wb') as files:
    pickle.dump(classifier,files)
with open('random_model.pkl','wb') as files:
    pickle.dump(random_classifier,files)
with open('nb_model.pkl','wb') as files:
    pickle.dump(nb_classifier,files)
with open('svm_model.pkl','wb') as files:
    pickle.dump(svm_classifier,files)